-- Legacy terminology rename: sprint -> workflow, job -> agent
-- Generated by scripts/pg/generate-rename-mapping.mjs from the live catalog.
-- Do not edit by hand: regenerate instead.
--
-- EXCEPTION (hand-edited): the rename statements for sprint_workflow_templates,
-- sprint_workflow_statuses and sprint_workflow_transitions were removed, because
-- migration 12 drops those tables outright. This migration had not been applied
-- anywhere when they were removed, so no checksum was invalidated. Regenerating
-- from the live catalog after 12 has been applied reproduces this file as-is.
--
-- ALTER ... RENAME is transactional and metadata-only in PostgreSQL: foreign keys,
-- indexes and constraints follow automatically, and the whole migration is one unit.

BEGIN;

-- 1. tables
ALTER TABLE "sprint_task_routing_rules" RENAME TO "workflow_task_routing_rules";
ALTER TABLE "sprint_task_statuses" RENAME TO "workflow_task_statuses";
ALTER TABLE "sprint_task_transition_requirement_tombstones" RENAME TO "workflow_task_transition_requirement_tombstones";
ALTER TABLE "sprint_task_transition_requirements" RENAME TO "workflow_task_transition_requirements";
ALTER TABLE "sprint_task_transitions" RENAME TO "workflow_task_transitions";
ALTER TABLE "sprint_type_outcomes" RENAME TO "workflow_type_outcomes";
ALTER TABLE "sprint_type_relationship_types" RENAME TO "workflow_type_relationship_types";
ALTER TABLE "sprint_type_task_statuses" RENAME TO "workflow_type_task_statuses";
ALTER TABLE "sprint_type_task_types" RENAME TO "workflow_type_task_types";
ALTER TABLE "sprint_types" RENAME TO "workflow_types";
ALTER TABLE "sprints" RENAME TO "workflows";

-- 2. columns
ALTER TABLE "agents" RENAME COLUMN "job_title" TO "title";
ALTER TABLE "agents" RENAME COLUMN "job_instructions" TO "instructions";
ALTER TABLE "agents" RENAME COLUMN "job_instructions_updated_at" TO "instructions_updated_at";
ALTER TABLE "external_event_mappings" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "external_event_mappings" RENAME COLUMN "sprint_type" TO "workflow_type";
ALTER TABLE "recurring_task_series" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "workflow_task_routing_rules" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "workflow_task_routing_rules" RENAME COLUMN "sprint_type" TO "workflow_type";
ALTER TABLE "workflow_task_statuses" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "workflow_task_transition_requirement_tombstones" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "workflow_task_transition_requirements" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "workflow_task_transition_requirements" RENAME COLUMN "sprint_type" TO "workflow_type";
ALTER TABLE "workflow_task_transitions" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "workflow_task_transitions" RENAME COLUMN "sprint_type" TO "workflow_type";
ALTER TABLE "workflow_type_outcomes" RENAME COLUMN "sprint_type_key" TO "workflow_type_key";
ALTER TABLE "workflow_type_relationship_types" RENAME COLUMN "sprint_type_key" TO "workflow_type_key";
ALTER TABLE "workflow_type_task_statuses" RENAME COLUMN "sprint_type_key" TO "workflow_type_key";
ALTER TABLE "workflow_type_task_types" RENAME COLUMN "sprint_type_key" TO "workflow_type_key";
ALTER TABLE "workflows" RENAME COLUMN "sprint_type" TO "workflow_type";
ALTER TABLE "story_point_model_routing" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "story_point_model_routing" RENAME COLUMN "sprint_type" TO "workflow_type";
ALTER TABLE "task_creation_events" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "task_events" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "task_field_schemas" RENAME COLUMN "sprint_type_key" TO "workflow_type_key";
ALTER TABLE "task_outcome_metrics" RENAME COLUMN "sprint_id" TO "workflow_id";
ALTER TABLE "tasks" RENAME COLUMN "sprint_id" TO "workflow_id";

-- 3. drop dead columns — each verified to hold zero values at generation time
--    agents.schedule has WRITERS in api/src/routes/agents.ts that must be removed
--    first, or agent create and update start failing on a missing column.
ALTER TABLE "agents" DROP COLUMN "sprint_id";  -- populated on 0 of 66 agents
ALTER TABLE "agents" DROP COLUMN "schedule";  -- populated on 0 of 66 agents
ALTER TABLE "task_creation_events" DROP COLUMN "job_id";  -- unpopulated, no foreign key
ALTER TABLE "task_outcome_metrics" DROP COLUMN "job_id";  -- unpopulated, no foreign key

-- 4. indexes (a table rename does not rename its indexes)
ALTER INDEX "idx_sprint_requirement_tombstones_sprint" RENAME TO "idx_workflow_requirement_tombstones_workflow";
ALTER INDEX "idx_sprint_task_routing_rules_candidate_unique" RENAME TO "idx_workflow_task_routing_rules_candidate_unique";
ALTER INDEX "idx_sprint_task_routing_rules_lookup" RENAME TO "idx_workflow_task_routing_rules_lookup";
ALTER INDEX "idx_sprint_task_routing_rules_scope_lookup" RENAME TO "idx_workflow_task_routing_rules_scope_lookup";
ALTER INDEX "idx_sprint_task_routing_rules_tenant" RENAME TO "idx_workflow_task_routing_rules_tenant";
ALTER INDEX "idx_sprint_task_statuses_lookup" RENAME TO "idx_workflow_task_statuses_lookup";
ALTER INDEX "idx_sprint_task_transition_requirements_lookup" RENAME TO "idx_workflow_task_transition_requirements_lookup";
ALTER INDEX "idx_sprint_task_transition_requirements_scope_lookup" RENAME TO "idx_workflow_task_transition_requirements_scope_lookup";
ALTER INDEX "idx_sprint_task_transition_requirements_tenant" RENAME TO "idx_workflow_task_transition_requirements_tenant";
ALTER INDEX "idx_sprint_task_transitions_lookup" RENAME TO "idx_workflow_task_transitions_lookup";
ALTER INDEX "idx_sprint_task_transitions_scope_lookup" RENAME TO "idx_workflow_task_transitions_scope_lookup";
ALTER INDEX "idx_sprint_task_transitions_tenant" RENAME TO "idx_workflow_task_transitions_tenant";
ALTER INDEX "idx_sprint_type_outcomes_lookup" RENAME TO "idx_workflow_type_outcomes_lookup";
ALTER INDEX "idx_sprint_type_relationship_types_lookup" RENAME TO "idx_workflow_type_relationship_types_lookup";
ALTER INDEX "idx_sprint_type_task_statuses_lookup" RENAME TO "idx_workflow_type_task_statuses_lookup";
ALTER INDEX "idx_sprint_type_task_types_lookup" RENAME TO "idx_workflow_type_task_types_lookup";
ALTER INDEX "idx_sprint_types_project" RENAME TO "idx_workflow_types_project";
ALTER INDEX "idx_sprint_types_system" RENAME TO "idx_workflow_types_system";
ALTER INDEX "idx_sprint_types_tenant_key" RENAME TO "idx_workflow_types_tenant_key";
ALTER INDEX "idx_sprints_project" RENAME TO "idx_workflows_project";
ALTER INDEX "idx_sprints_status" RENAME TO "idx_workflows_status";
ALTER INDEX "idx_sprints_tenant" RENAME TO "idx_workflows_tenant";
ALTER INDEX "idx_tce_sprint" RENAME TO "idx_tce_workflow";
ALTER INDEX "idx_tom_sprint" RENAME TO "idx_tom_workflow";
ALTER INDEX "sprint_task_routing_rules_pkey" RENAME TO "workflow_task_routing_rules_pkey";
ALTER INDEX "sprint_task_statuses_pkey" RENAME TO "workflow_task_statuses_pkey";
ALTER INDEX "sprint_task_transition_requirement_tombstones_pkey" RENAME TO "workflow_task_transition_requirement_tombstones_pkey";
ALTER INDEX "sprint_task_transition_requirements_pkey" RENAME TO "workflow_task_transition_requirements_pkey";
ALTER INDEX "sprint_task_transitions_pkey" RENAME TO "workflow_task_transitions_pkey";
ALTER INDEX "sprint_type_outcomes_pkey" RENAME TO "workflow_type_outcomes_pkey";
ALTER INDEX "sprint_type_relationship_types_pkey" RENAME TO "workflow_type_relationship_types_pkey";
ALTER INDEX "sprint_type_task_statuses_pkey" RENAME TO "workflow_type_task_statuses_pkey";
ALTER INDEX "sprint_type_task_types_pkey" RENAME TO "workflow_type_task_types_pkey";
ALTER INDEX "sprint_types_pkey" RENAME TO "workflow_types_pkey";
ALTER INDEX "sprints_pkey" RENAME TO "workflows_pkey";

COMMIT;
