'use client';

import { useEffect, useState } from 'react';
import { Archive, Download, History, Play, Plus, Save, Upload, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { telemetryClient } from '@/lib/api/telemetry';
import type { MetricDefinition, TelemetryBinding, TelemetryMetric, TelemetryProfile, TelemetryReport, TelemetryReportDefinition, TelemetryResource, TelemetryScope } from '@/lib/telemetryTypes';
import { parseTelemetryDraft, telemetryErrorMessage, telemetryBindingScopeLabel } from '@/lib/telemetryPresentation';
import { BindingHealthNotice, ErrorNotice, Field, inputClass, JsonDetails, Select } from './TelemetryControls';
import TelemetryBindingInspector from './TelemetryBindingInspector';
import { telemetryBindingPreviewRequest, telemetryBindingWrite, type TelemetryBindingReview } from '@/lib/telemetryBindings';

type Tab = 'metrics' | 'reports' | 'bindings' | 'profiles' | 'portability';
export interface LibraryData { metrics: TelemetryMetric[]; reports: TelemetryReport[]; profiles: TelemetryProfile[]; bindings: TelemetryBinding[] }
export default function TelemetryLibrary({ tab, scope, data, reload, onEditMetric, onRunMetric, onRunReport, onPreviewReport, onRunFamily, onOpenSnapshot, lastQueryId, lastReportId }: {
  tab: Tab; scope: TelemetryScope; data: LibraryData; reload: () => Promise<void>; onEditMetric: (metric: TelemetryMetric) => void;
  onRunMetric: (metric: TelemetryMetric) => void; onRunReport: (report: TelemetryReport) => void; onPreviewReport: (definition: TelemetryReportDefinition) => void;
  onRunFamily: (key: string) => void; onOpenSnapshot: (id: string) => void; lastQueryId?: string; lastReportId?: string;
}) {
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [history, setHistory] = useState<TelemetryResource<unknown> | null>(null);
  const [reportDraft, setReportDraft] = useState<TelemetryReport | null | undefined>(undefined);
  const [reportName, setReportName] = useState('');
  const [reportKey, setReportKey] = useState('');
  const [reportDefinition, setReportDefinition] = useState<TelemetryReportDefinition>({ metrics: [], scope, timezone: 'UTC' });
  const [profileDraft, setProfileDraft] = useState<TelemetryProfile | null | undefined>(undefined);
  const [profileName, setProfileName] = useState('');
  const [profileKey, setProfileKey] = useState('');
  const [profileText, setProfileText] = useState('{\n  "signals": {}\n}');
  const [binding, setBinding] = useState<TelemetryBinding>({ family_key: '', scope, disabled: false });
  const [bindingReview, setBindingReview] = useState<TelemetryBindingReview | null>(null);
  const [bundleText, setBundleText] = useState('');
  const [referenceText, setReferenceText] = useState('{}');
  const [importResult, setImportResult] = useState<Record<string, unknown> | null>(null);
  const [snapshots, setSnapshots] = useState<{ reportName: string; rows: Record<string, unknown>[] } | null>(null);
  useEffect(() => { setBinding({ family_key: '', scope, disabled: false }); setHistory(null); setReportDraft(undefined); setProfileDraft(undefined); setError(null); setNotice(null); }, [scope]);
  async function perform(action: () => Promise<void>) {
    setBusy(true); setError(null); setNotice(null);
    try { await action(); } catch (cause) { setError(telemetryErrorMessage(cause)); } finally { setBusy(false); }
  }
  function editReport(report?: TelemetryReport) {
    setReportDraft(report ?? null); setReportName(report?.name ?? ''); setReportKey(report?.key ?? '');
    setReportDefinition(report ? structuredClone(report.definition) : { metrics: [], scope, timezone: 'UTC' });
  }
  function editProfile(profile?: TelemetryProfile) {
    setProfileDraft(profile ?? null); setProfileName(profile?.name ?? ''); setProfileKey(profile?.key ?? '');
    setProfileText(JSON.stringify(profile?.definition ?? { signals: {} }, null, 2));
  }
  const metricOptions = data.metrics.map(metric => ({ value: metric.latest_revision_id, label: `${metric.name} · revision ${metric.revision}` }));
  const bindingReviewKey = JSON.stringify(telemetryBindingPreviewRequest(binding, scope));
  const bindingReady = Boolean(bindingReview?.preview.proposed && bindingReview.requestKey === bindingReviewKey);
  const scopeDescription = Object.entries(scope).filter(([key, value]) => key !== 'include_archived' && value != null).map(([key, value]) => `${key.replace(/_/g, ' ')} ${value}`).join(' · ') || 'Tenant defaults';
  return <div className="space-y-4">
    <ErrorNotice message={error}/>{notice && <p role="status" className="rounded-lg border border-emerald-500/30 bg-emerald-950/20 p-3 text-sm text-emerald-200">{notice}</p>}
    {tab === 'metrics' && <>
      <div><h2 className="font-semibold text-white">Metric library</h2><p className="mt-1 text-sm text-slate-400">Each revision preserves its definition. Open one in the explorer to compare proposed changes before saving.</p></div>
      {!data.metrics.length && <Card><p className="text-sm text-slate-400">No saved metrics in this scope. Create a metric in the explorer, preview its evidence, then save it.</p></Card>}
      {data.metrics.map(metric => <Card key={metric.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-medium text-white">{metric.name} <span className="ml-2 text-xs font-normal text-slate-500">v{metric.revision}</span></h3><p className="mt-1 text-xs text-slate-500">{metric.key} · {telemetryBindingScopeLabel(metric.scope ?? {})}</p><p className="mt-2 text-sm text-slate-400">{metric.definition.description ?? `${metric.definition.grain} · ${metric.definition.measure.kind} · ${metric.definition.time_basis.replace(/_/g, ' ')}`}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => onRunMetric(metric)}><Play className="h-3 w-3"/>Run</Button><Button size="sm" variant="ghost" onClick={() => onEditMetric(metric)}>Edit definition</Button><Button size="sm" variant="ghost" onClick={() => perform(async () => setHistory(await telemetryClient.getTelemetryResource<MetricDefinition>('metrics', metric.id)))}><History className="h-3 w-3"/>Revisions</Button><Button size="sm" variant="ghost" onClick={() => perform(async () => { await telemetryClient.archiveTelemetryResource('metrics', metric.id); await reload(); setNotice('Metric archived. Existing pinned revisions are preserved.'); })}><Archive className="h-3 w-3"/>Archive</Button></div></div></Card>)}
    </>}
    {tab === 'reports' && <>
      <div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-white">Saved reports</h2><p className="mt-1 text-sm text-slate-400">Reports pin metric revisions. Refresh retrieves new evidence using the same definitions.</p></div><Button size="sm" onClick={() => editReport()}><Plus className="h-3 w-3"/>New report</Button></div>
      {reportDraft !== undefined && <Card><div className="mb-4 flex items-center justify-between"><h3 className="font-medium text-white">{reportDraft ? 'Revise report' : 'Create report'}</h3><Button variant="ghost" size="sm" onClick={() => setReportDraft(undefined)} aria-label="Close report editor"><X className="h-4 w-4"/></Button></div>
        <div className="grid gap-3 sm:grid-cols-2"><Field label="Report name"><input className={inputClass} value={reportName} onChange={event => setReportName(event.target.value)}/></Field><Field label="Stable key"><input className={inputClass} value={reportKey} disabled={Boolean(reportDraft)} onChange={event => setReportKey(event.target.value)}/></Field></div>
        <div className="mt-4 space-y-2"><p className="text-xs text-slate-400">Select saved metric revisions</p>{data.metrics.map(metric => {
          const selection = reportDefinition.metrics.find(item => item.metric_revision_id === metric.latest_revision_id || item.metric_id === metric.id);
          return <div key={metric.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-slate-700/50 p-3"><label className="flex flex-1 items-center gap-2 text-sm text-slate-200"><input type="checkbox" checked={Boolean(selection)} onChange={event => setReportDefinition({ ...reportDefinition, metrics: event.target.checked ? [...reportDefinition.metrics, { metric_id: metric.id, metric_revision_id: metric.latest_revision_id, title: metric.name, display: 'card' }] : reportDefinition.metrics.filter(item => item !== selection) })}/>{metric.name}<span className="text-xs text-slate-500">{selection && selection.metric_revision_id !== metric.latest_revision_id ? 'Earlier pinned revision' : `v${metric.revision}`}</span></label>{selection && <select aria-label={`${metric.name} display`} className={`${inputClass} max-w-32`} value={selection.display ?? 'card'} onChange={event => setReportDefinition({ ...reportDefinition, metrics: reportDefinition.metrics.map(item => item === selection ? { ...item, display: event.target.value as 'card' } : item) })}><option value="card">Card</option><option value="table">Table</option><option value="bar">Bars</option><option value="line">Time series</option><option value="funnel">Funnel</option></select>}</div>;
        })}</div>
        {reportDefinition.metrics.filter(item => !data.metrics.some(metric => metric.latest_revision_id === item.metric_revision_id || item.metric_id === metric.id)).map(item => <p key={item.metric_revision_id} className="mt-2 text-xs text-amber-200">Retained pinned measurement: {item.title ?? item.metric_revision_id}. Its family is not in this library listing.</p>)}
        <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" disabled={!reportDefinition.metrics.length} onClick={() => onPreviewReport(reportDefinition)}>Preview selected definitions</Button>{reportDraft && <Button size="sm" variant="ghost" onClick={() => { setReportDefinition({ ...reportDefinition, metrics: reportDefinition.metrics.map(item => { const metric = data.metrics.find(candidate => candidate.id === item.metric_id || candidate.latest_revision_id === item.metric_revision_id); return metric ? { ...item, metric_revision_id: metric.latest_revision_id } : item; }) }); setNotice('Draft pins updated to latest visible revisions. Preview the impact before saving this report revision.'); }}>Update draft to latest definitions</Button>}<Button size="sm" variant="primary" loading={busy} disabled={!reportName.trim() || !reportKey.trim() || !reportDefinition.metrics.length} onClick={() => perform(async () => {
          const definition = { ...reportDefinition, scope: reportDraft?.definition.scope ?? scope };
          if (reportDraft) await telemetryClient.reviseTelemetryReport(reportDraft.id, { definition, name: reportName, expected_revision_id: reportDraft.latest_revision_id });
          else await telemetryClient.createTelemetryReport({ key: reportKey, name: reportName, scope, definition });
          await reload(); setReportDraft(undefined); setNotice('Report saved with explicit pinned metric revisions.');
        })}><Save className="h-3 w-3"/>Save report</Button></div><div className="mt-3"><JsonDetails label="Pinned report definition" value={reportDefinition}/></div>
      </Card>}
      {!data.reports.length && reportDraft === undefined && <Card><p className="text-sm text-slate-400">No saved reports in this scope. Save a metric first, then add it to a report.</p></Card>}
      {data.reports.map(report => <Card key={report.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium text-white">{report.name} <span className="ml-2 text-xs text-slate-500">v{report.revision}</span></h3><p className="mt-1 text-xs text-slate-400">{report.definition.metrics.length} pinned measurements</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => onRunReport(report)}><Play className="h-3 w-3"/>Open report</Button><Button size="sm" variant="ghost" onClick={() => editReport(report)}>Edit</Button><Button size="sm" variant="ghost" onClick={() => perform(async () => setHistory(await telemetryClient.getTelemetryResource('reports', report.id)))}>Revisions</Button><Button size="sm" variant="ghost" onClick={() => perform(async () => setSnapshots({ reportName: report.name, rows: (await telemetryClient.getTelemetrySnapshots(report.id)).snapshots }))}>Snapshots</Button>{lastReportId === report.id && lastQueryId && <Button size="sm" variant="ghost" onClick={() => perform(async () => { await telemetryClient.freezeTelemetryReport(report.id, { query_id: lastQueryId, report_revision_id: report.latest_revision_id }); setNotice('Report snapshot frozen with its calculation and evidence.'); })}>Freeze displayed result</Button>}<Button size="sm" variant="ghost" onClick={() => perform(async () => { await telemetryClient.archiveTelemetryResource('reports', report.id); await reload(); setNotice('Report archived.'); })}><Archive className="h-3 w-3"/></Button></div></div></Card>)}
      {snapshots && <Card><div className="mb-3 flex justify-between"><h3 className="text-sm font-medium text-white">{snapshots.reportName} snapshots</h3><Button size="sm" variant="ghost" onClick={() => setSnapshots(null)}><X className="h-3 w-3"/></Button></div>{!snapshots.rows.length ? <p className="text-sm text-slate-400">No frozen snapshots yet.</p> : snapshots.rows.map((row, index) => <div key={index} className="mb-3 rounded-lg border border-slate-700/50 p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs text-slate-400">{String(row.created_at ?? `Snapshot ${index + 1}`)}</span><Button size="sm" onClick={() => onOpenSnapshot(String(row.query_id))}>Open frozen result</Button></div><JsonDetails label="Snapshot metadata" value={row}/></div>)}</Card>}
    </>}
    {tab === 'bindings' && <>
      <div><h2 className="font-semibold text-white">Scoped meanings</h2><p className="mt-1 text-sm text-slate-400">Bind a family to a metric revision at this scope. More specific workflow and task-type bindings override broader defaults. An explicit disable stops inheritance.</p></div>
      <Card><p className="mb-4 text-xs text-slate-400">Editing: {scopeDescription}</p><div className="mb-4"><Button size="sm" disabled={!binding.family_key} onClick={() => onRunFamily(binding.family_key)}>Run effective metric for this scope</Button></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Metric family key"><input list="telemetry-family-keys" className={inputClass} value={binding.family_key} onChange={event => setBinding({ ...binding, family_key: event.target.value })}/><datalist id="telemetry-family-keys">{data.metrics.map(metric => <option key={metric.id} value={metric.key}/>)}</datalist></Field><Select label="Pinned metric revision" value={binding.metric_revision_id ?? ''} onChange={value => setBinding({ ...binding, metric_revision_id: value || null })} options={[{ value: '', label: 'Choose a saved revision' }, ...metricOptions]} disabled={binding.disabled}/><Select label="Optional profile revision" value={binding.profile_revision_id ?? ''} onChange={value => setBinding({ ...binding, profile_revision_id: value || null })} options={[{ value: '', label: 'No reusable profile' }, ...data.profiles.map(profile => ({ value: profile.latest_revision_id, label: `${profile.name} · v${profile.revision}` }))]}/><label className="flex items-center gap-2 self-end py-2 text-sm text-slate-300"><input type="checkbox" checked={Boolean(binding.disabled)} onChange={event => setBinding({ ...binding, disabled: event.target.checked })}/>Disable this family at this scope</label></div><TelemetryBindingInspector binding={binding} scope={scope} metrics={data.metrics} refreshKey={JSON.stringify(data.bindings.map(item => [item.id, item.version]))} onReviewed={setBindingReview}/><Button className="mt-4" size="sm" variant="primary" loading={busy} disabled={!bindingReady} onClick={() => perform(async () => { await telemetryClient.saveTelemetryBinding(telemetryBindingWrite(binding, scope, bindingReview)); await reload(); setNotice('Scoped binding saved.'); })}><Save className="h-3 w-3"/>Save binding</Button></Card>
      {data.bindings.map((item, index) => <Card key={item.id ?? index}><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm text-white">{item.family_key} <Badge variant={item.disabled ? 'warn' : 'info'}>{item.disabled ? 'Disabled' : telemetryBindingScopeLabel(item.scope)}</Badge></h3><p className="mt-2 text-xs text-slate-400">{Object.entries(item.scope).map(([key, value]) => `${key}: ${value}`).join(' · ') || 'Tenant default'}</p><p className="mt-1 text-xs text-slate-500">Revision {item.metric_revision_id ?? 'none'}</p><BindingHealthNotice binding={item}/></div><Button size="sm" variant="ghost" onClick={() => { setBinding({ family_key: item.family_key, scope, metric_revision_id: item.metric_revision_id, profile_revision_id: item.profile_revision_id, disabled: item.disabled, version: Object.entries(item.scope).every(([key, value]) => (scope as Record<string, unknown>)[key] === value) && Object.keys(scope).filter(key => key !== 'include_archived' && (scope as Record<string, unknown>)[key] != null).length === Object.keys(item.scope).length ? item.version : undefined }); setNotice('Editing this family at the currently selected scope.'); }}>Override here</Button></div></Card>)}
    </>}
    {tab === 'profiles' && <>
      <div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-white">Measurement profiles</h2><p className="mt-1 text-sm text-slate-400">Reusable named signals; optional for ordinary numeric measurements.</p></div><Button size="sm" onClick={() => editProfile()}><Plus className="h-3 w-3"/>New profile</Button></div>
      {profileDraft !== undefined && <Card><div className="grid gap-3 sm:grid-cols-2"><Field label="Profile name"><input className={inputClass} value={profileName} onChange={event => setProfileName(event.target.value)}/></Field><Field label="Stable key"><input className={inputClass} value={profileKey} disabled={Boolean(profileDraft)} onChange={event => setProfileKey(event.target.value)}/></Field></div><div className="mt-3"><Field label="Signals" hint="Map names such as success or rework to catalog-backed predicates."><textarea spellCheck={false} className={`${inputClass} min-h-60 font-mono text-xs`} value={profileText} onChange={event => setProfileText(event.target.value)}/></Field></div><div className="mt-3 flex gap-2"><Button size="sm" loading={busy} variant="primary" disabled={!profileName || !profileKey} onClick={() => perform(async () => { await telemetryClient.saveTelemetryProfile({ name: profileName, key: profileKey, scope, definition: parseTelemetryDraft(profileText) as TelemetryProfile['definition'] }, profileDraft ?? undefined); await reload(); setProfileDraft(undefined); setNotice('Profile revision saved.'); })}>Save profile</Button><Button size="sm" variant="ghost" onClick={() => setProfileDraft(undefined)}>Cancel</Button></div></Card>}
      {data.profiles.map(profile => <Card key={profile.id}><div className="flex justify-between"><h3 className="text-sm font-medium text-white">{profile.name} · v{profile.revision}</h3><Button size="sm" variant="ghost" onClick={() => editProfile(profile)}>Edit</Button></div><JsonDetails label="Configured signals" value={profile.definition}/></Card>)}
      {!data.profiles.length && profileDraft === undefined && <p className="text-sm text-slate-400">No profiles saved. Define signals directly in the metric builder or add a reusable profile.</p>}
    </>}
    {tab === 'portability' && <Card><h2 className="font-semibold text-white">Export and import definitions</h2><p className="mt-2 text-sm text-slate-400">Export the visible scoped definitions. Import into the selected destination scope, mapping canonical field references to their destination catalog identities.</p><Button className="mt-4" size="sm" loading={busy} onClick={() => perform(async () => { const bundle = await telemetryClient.exportTelemetry({ scope }); const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'agent-hq-telemetry.json'; anchor.click(); URL.revokeObjectURL(url); setNotice('Definition bundle exported.'); })}><Download className="h-3 w-3"/>Export this scope</Button>
      <div className="mt-6 space-y-3"><Field label="Import bundle"><textarea spellCheck={false} className={`${inputClass} min-h-44 font-mono text-xs`} value={bundleText} onChange={event => setBundleText(event.target.value)} placeholder="Paste an exported JSON bundle"/></Field><Field label="Reference mapping" hint='JSON object: {"source-field-id": "destination-field-id"}'><textarea spellCheck={false} className={`${inputClass} min-h-24 font-mono text-xs`} value={referenceText} onChange={event => setReferenceText(event.target.value)}/></Field><p className="text-xs text-slate-500">Destination: {scopeDescription}. Unresolved references must be reported; broken definitions are not activated.</p><Button size="sm" variant="primary" loading={busy} disabled={!bundleText.trim()} onClick={() => perform(async () => { const response = await telemetryClient.importTelemetry({ bundle: parseTelemetryDraft(bundleText), scope, reference_map: parseTelemetryDraft(referenceText) as Record<string, string> }); setImportResult(response); await reload(); setNotice('Import request completed. Review its validation results below.'); })}><Upload className="h-3 w-3"/>Import definitions</Button>{importResult && <JsonDetails label="Import results" value={importResult}/>}</div>
    </Card>}
    {history && <Card><div className="mb-4 flex justify-between"><h3 className="text-sm font-medium text-white">{history.name}: immutable revisions</h3><Button size="sm" variant="ghost" onClick={() => setHistory(null)}><X className="h-3 w-3"/></Button></div>{(history.revisions ?? []).map(revision => <div key={revision.id} className="mb-3 rounded-lg border border-slate-700/50 p-3"><p className="mb-2 text-xs text-slate-400">Revision {revision.revision} {revision.created_at ? `· ${new Date(revision.created_at).toLocaleString()}` : ''}</p><JsonDetails label="Definition" value={revision.definition}/></div>)}</Card>}
  </div>;
}
