'use client';
import { X } from 'lucide-react';
import { availableTelemetryDisplays } from '@/lib/telemetryViews';
import { moveDashboardBlock, operationLabels, updateDashboardBlock } from '@/lib/dashboardLayout';
import type { DashboardBlock, DashboardDocument, DashboardDraft, DashboardIcon, DashboardOperation } from '@/lib/dashboardTypes';
import type { TelemetryCatalog, TelemetryDisplay, TelemetryWidget } from '@/lib/telemetryTypes';
import type { DashboardMetricState } from './useDashboardData';
import { dashboardIcons } from './DashboardBlocks';
import styles from './dashboard.module.css';

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className={styles.field}><span>{label}</span>{children}</label>;
export default function DashboardInspector({ draft, block, data, catalog, change, close }: { draft: DashboardDraft; block?: DashboardBlock; data: Record<string, DashboardMetricState>; catalog: TelemetryCatalog | null; change: (draft: DashboardDraft) => void; close: () => void }) {
  const page = draft.definition;
  const changePage = (definition: DashboardDocument) => change({ ...draft, definition });
  const patch = (values: Partial<DashboardBlock>) => { if (block) changePage(updateDashboardBlock(page, block.id, current => ({ ...current, ...values }) as DashboardBlock)); };
  const binding = block?.type === 'metric' ? page.metrics.find(metric => metric.id === block.binding_id) : undefined;
  const state = binding ? data[binding.id] : undefined;
  const patchBinding = (values: Partial<TelemetryWidget>) => { if (binding) changePage({ ...page, metrics: page.metrics.map(metric => metric.id === binding.id ? { ...metric, ...values } : metric) }); };
  const column = block ? page.sections.flatMap(section => section.columns).find(item => item.blocks.some(item => item.id === block.id)) : undefined;
  return <aside className={`${styles.inspector} ${styles.panel}`} aria-label={block ? 'Block settings' : 'Page settings'}><div className={styles.inspectorHeader}><h2 className={styles.sectionTitle}>{block ? 'Block settings' : 'Page settings'}</h2>{block && <button type="button" className={styles.button} onClick={close} aria-label="Close block settings"><X/></button>}</div>
    {!block ? <><Field label="Dashboard name"><input className={styles.input} value={draft.name} maxLength={200} onChange={event => change({ ...draft, name: event.target.value })}/></Field><Field label="Description"><textarea className={styles.input} maxLength={2000} value={page.description ?? ''} onChange={event => changePage({ ...page, description: event.target.value })}/></Field><Field label="Page width"><select className={styles.input} value={page.appearance.width} onChange={event => changePage({ ...page, appearance: { ...page.appearance, width: event.target.value as 'standard' | 'wide' } })}><option value="wide">Wide</option><option value="standard">Standard</option></select></Field><Field label="Density"><select className={styles.input} value={page.appearance.density} onChange={event => changePage({ ...page, appearance: { ...page.appearance, density: event.target.value as 'compact' | 'comfortable' } })}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><p className={styles.muted}>Use + Add block or press / to insert content. Select a block’s settings to customize it. Drag handles move blocks between columns.</p></> : <>
      <Field label="Title"><input className={styles.input} maxLength={200} value={block.title ?? ''} placeholder="Use source title" onChange={event => patch({ title: event.target.value })}/></Field>
      {'text' in block && <Field label={block.type === 'heading' ? 'Heading text' : 'Text · Markdown supported'}><textarea className={styles.input} maxLength={12000} value={block.text} onChange={event => patch({ text: event.target.value })}/></Field>}
      {block.type === 'link' && <Field label="Link URL"><input className={styles.input} value={block.url} onChange={event => patch({ url: event.target.value })}/></Field>}
      {!['heading', 'divider'].includes(block.type) && <Field label="Appearance"><select className={styles.input} value={block.surface ?? 'card'} onChange={event => patch({ surface: event.target.value as 'card' | 'plain' })}><option value="card">Card</option><option value="plain">Plain</option></select></Field>}
      {['metric', 'operation'].includes(block.type) && <><Field label="Accent color"><select className={styles.input} value={block.accent ?? 'neutral'} onChange={event => patch({ accent: event.target.value as DashboardBlock['accent'] })}>{['neutral', 'blue', 'amber', 'green', 'cyan', 'violet', 'red'].map(color => <option key={color} value={color}>{color[0].toUpperCase() + color.slice(1)}</option>)}</select></Field><Field label="Icon"><select className={styles.input} value={block.icon ?? 'activity'} onChange={event => patch({ icon: event.target.value as DashboardIcon })}>{Object.keys(dashboardIcons).map(icon => <option key={icon} value={icon}>{icon}</option>)}</select></Field></>}
      {block.type === 'operation' && <Field label="Operational data"><select className={styles.input} value={block.operation} onChange={event => patch({ operation: event.target.value as DashboardOperation })}>{Object.entries(operationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>}
      {block.type === 'comparison' && <><Field label="Visible rows"><input type="number" className={styles.input} min={3} max={50} value={block.rows ?? 9} onChange={event => patch({ rows: Math.max(3, Math.min(50, Number(event.target.value))) })}/></Field><Field label="Sort groups"><select className={styles.input} value={block.sort ?? 'label'} onChange={event => patch({ sort: event.target.value as 'label' | 'value_desc' | 'value_asc' })}><option value="label">Group name</option><option value="value_desc">Largest first</option><option value="value_asc">Smallest first</option></select></Field>{block.sort && block.sort !== 'label' && <Field label="Sort by metric"><select className={styles.input} value={block.sort_by ?? block.binding_ids[0] ?? ''} onChange={event => patch({ sort_by: event.target.value })}>{block.binding_ids.map(id => <option key={id} value={id}>{page.metrics.find(metric => metric.id === id)?.title || data[id]?.definition?.name || id}</option>)}</select></Field>}<p className={styles.muted}>Choose columns in display order.</p>{page.metrics.map(metric => <label key={metric.id} className={`${styles.field} !flex-row items-center mt-3`}><input type="checkbox" checked={block.binding_ids.includes(metric.id)} disabled={block.binding_ids.length === 1 && block.binding_ids.includes(metric.id)} onChange={event => patch({ binding_ids: event.target.checked ? [...block.binding_ids, metric.id] : block.binding_ids.filter(id => id !== metric.id), sort_by: !event.target.checked && block.sort_by === metric.id ? undefined : block.sort_by })}/>{metric.title || data[metric.id]?.definition?.name || 'Metric'}</label>)}</>}
      {block.type === 'metric' && binding && <>
        <Field label="Presentation"><select className={styles.input} value={block.display ?? 'card'} onChange={event => {
          const display = event.target.value as TelemetryDisplay;
          let next = updateDashboardBlock(page, block.id, current => ({ ...current, display }) as DashboardBlock);
          if (display === 'line' && !binding.view?.bucket) next = { ...next, metrics: next.metrics.map(metric => metric.id === binding.id ? { ...metric, view: { ...metric.view, bucket: 'day' } } : metric) };
          changePage(next);
        }}>{availableTelemetryDisplays(state?.definition).map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></Field>
        <Field label="Decimal places"><select className={styles.input} value={block.precision ?? 2} onChange={event => patch({ precision: Number(event.target.value) })}>{[0, 1, 2, 3, 4, 5, 6].map(count => <option value={count} key={count}>{count}</option>)}</select></Field>
        <details><summary className={`${styles.muted} cursor-pointer mb-3`}>Data & filters</summary><p className={`${styles.muted} mb-3`}>This source is shared by duplicate blocks. Its saved metric calculation stays pinned.</p>
          <Field label="Breakdown"><select className={styles.input} value={binding.view?.group_by?.length === 0 ? '' : binding.view?.group_by?.length === 1 && 'field' in binding.view.group_by[0] ? binding.view.group_by[0].field : '__saved__'} onChange={event => { if (event.target.value !== '__saved__') patchBinding({ view: { ...binding.view, group_by: event.target.value ? [{ field: event.target.value }] : [] } }); }}><option value="__saved__">Saved breakdown</option><option value="">One total</option>{['agent_id', 'project_id', 'workflow_id', 'task_type', 'status'].map(field => <option key={field} value={field}>{field.replace('_id', '').replace('_', ' ')}</option>)}{catalog?.fields.filter(field => field.id.startsWith('field_') && !field.retired).map(field => <option key={field.id} value={field.id}>{field.label}</option>)}</select></Field>
          <Field label="Narrow to project"><select className={styles.input} value={binding.view?.scope?.project_id ?? ''} onChange={event => patchBinding({ view: { ...binding.view, scope: { ...binding.view?.scope, project_id: event.target.value ? Number(event.target.value) : undefined } } })}><option value="">Follow dashboard / metric scope</option>{catalog?.projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></Field>
          {state?.definition?.time_basis !== 'current' && <><Field label="Time bucket"><select className={styles.input} value={binding.view?.bucket ?? ''} onChange={event => patchBinding({ view: { ...binding.view, bucket: (event.target.value || null) as NonNullable<TelemetryWidget['view']>['bucket'] } })}><option value="">Whole interval</option>{['hour', 'day', 'week', 'month'].map(value => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="From override · ISO timestamp"><input className={styles.input} value={binding.view?.from ?? ''} placeholder="Follow dashboard" onChange={event => patchBinding({ view: { ...binding.view, from: event.target.value || undefined } })}/></Field><Field label="To override · ISO timestamp"><input className={styles.input} value={binding.view?.to ?? ''} placeholder="Follow dashboard" onChange={event => patchBinding({ view: { ...binding.view, to: event.target.value || undefined } })}/></Field></>}
          <p className={styles.muted}>{state?.definition?.time_basis === 'current' ? 'Current snapshot · historical dates do not apply.' : 'Uses recorded history.'}</p>
        </details>
      </>}
      <Field label="Move to column"><select className={styles.input} value={column?.id ?? ''} onChange={event => changePage(moveDashboardBlock(page, block.id, event.target.value))}>{page.sections.flatMap((section, i) => section.columns.map((column, j) => <option key={column.id} value={column.id}>{section.title || `Section ${i + 1}`} · column {j + 1}</option>))}</select></Field>
    </>}
  </aside>;
}
