'use client';
import { createClientId } from '@/lib/clientId';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core';
import { SortableContext, rectSortingStrategy, sortableKeyboardCoordinates } from '@dnd-kit/sortable';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { telemetryClient } from '@/lib/api/telemetry';
import { telemetryErrorMessage } from '@/lib/telemetryPresentation';
import { moveTelemetryWidget } from '@/lib/telemetryViews';
import type { TelemetryCatalog, TelemetryMetric, TelemetryReport, TelemetryScope, TelemetryWidget } from '@/lib/telemetryTypes';
import { ErrorNotice, Field, inputClass, Select } from '../telemetry/TelemetryControls';
import MetricDashboardWidget from './MetricDashboardWidget';
import OperationalDashboard from './OperationalDashboard';

export default function MetricDashboards(){
  const [reports,setReports]=useState<TelemetryReport[]>([]),[metrics,setMetrics]=useState<TelemetryMetric[]>([]),[catalog,setCatalog]=useState<TelemetryCatalog|null>(null);
  const [selected,setSelected]=useState('overview'),[name,setName]=useState('My dashboard'),[widgets,setWidgets]=useState<TelemetryWidget[]>([]);
  const [scope,setScope]=useState<TelemetryScope>({include_archived:true}),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const [editing,setEditing]=useState(false),[dirty,setDirty]=useState(false),[refresh,setRefresh]=useState(0),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
  const [error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[viewId,setViewId]=useState('');
  const current=reports.find(report=>report.id===selected),dashboards=reports.filter(report=>report.definition.presentation==='dashboard'),views=reports.filter(report=>report.definition.presentation==='view');
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
  useEffect(()=>{const controller=new AbortController();Promise.all([telemetryClient.getTelemetryCatalog(undefined,controller.signal),telemetryClient.getTelemetryMetrics(undefined,controller.signal),telemetryClient.getTelemetryReports(undefined,controller.signal)]).then(([nextCatalog,nextMetrics,nextReports])=>{if(!controller.signal.aborted){setCatalog(nextCatalog);setMetrics(nextMetrics.metrics);setReports(nextReports.reports);if(new URLSearchParams(window.location.search).get('dashboard')==='builder'){setSelected('new');setEditing(true);}}}).catch(cause=>{if(!controller.signal.aborted)setError(telemetryErrorMessage(cause));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
  useEffect(()=>{if(!dirty)return;const prevent=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
  function select(id:string){const report=reports.find(item=>item.id===id);setSelected(id);setName(report?.name??'My dashboard');setWidgets((report?.definition.metrics??[]).map(widget=>({...widget,id:widget.id??createClientId()})));setScope(report?.definition.scope??report?.scope??{include_archived:true});setFrom(report?.definition.from??'');setTo(report?.definition.to??'');setDirty(false);setEditing(id==='new');setError(null);setNotice(null);setRefresh(value=>value+1);}
  function change(next:TelemetryWidget[]){setWidgets(next);setDirty(true);setNotice(null);}
  async function save(){setSaving(true);setError(null);try{if(!name.trim())throw new Error('Give the dashboard a name.');if(!widgets.length)throw new Error('Add at least one saved view.');const definition={presentation:'dashboard' as const,metrics:widgets,scope,from:from||undefined,to:to||undefined,timezone:'UTC'};const saved=current?await telemetryClient.reviseTelemetryReport(current.id,{definition,expected_revision_id:current.latest_revision_id,name:name.trim()}):await telemetryClient.createTelemetryReport({key:`dashboard_${createClientId()}`,name:name.trim(),scope,definition});setReports(items=>[...items.filter(item=>item.id!==saved.id),saved]);setSelected(saved.id);setEditing(false);setDirty(false);setNotice('Dashboard saved. Metric revisions and widget settings are pinned.');setRefresh(value=>value+1);}catch(cause){setError(telemetryErrorMessage(cause));}finally{setSaving(false);}}
  return <div><div className="mx-auto max-w-[1800px] space-y-4 p-4 md:px-8 md:pt-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div className="min-w-64"><Select label="Dashboard" value={selected} onChange={select} disabled={dirty} options={[{value:'overview',label:'Operational overview'},...dashboards.map(report=>({value:report.id,label:report.name})),...(selected==='new'?[{value:'new',label:'New dashboard'}]:[])]}/></div><div className="flex flex-wrap gap-2">{!dirty&&<Button type="button" disabled={loading} onClick={()=>select('new')}>New dashboard</Button>}{selected!=='overview'&&<><Button type="button" onClick={()=>setRefresh(value=>value+1)}>Refresh dashboard</Button>{editing?<><Button type="button" loading={saving} onClick={save}>Save dashboard</Button><Button type="button" disabled={saving} onClick={()=>select(current?.id??'overview')}>Cancel edits</Button></>:<Button type="button" onClick={()=>setEditing(true)}>Edit dashboard</Button>}</>}</div></div>
    <ErrorNotice message={error}/>{notice&&<p role="status" className="text-sm text-emerald-200">{notice}</p>}
    {selected!=='overview'&&<>
      <Card><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{editing?<Field label="Dashboard name"><input className={inputClass} value={name} onChange={event=>{setName(event.target.value);setDirty(true);}}/></Field>:<div><h1 className="text-xl font-semibold text-white">{name}</h1><p className="mt-2 text-xs text-slate-400">{widgets.length} widgets · pinned metric revisions</p></div>}<Select label="Shared project filter" value={String(scope.project_id??'')} disabled={Boolean(current?.scope?.project_id)} onChange={value=>{setScope({...scope,project_id:value?Number(value):undefined,workflow_id:undefined,workflow_type:undefined,task_type:undefined});if(editing)setDirty(true);}} options={[{value:'',label:'All authorized projects'},...(catalog?.projects.map(project=>({value:String(project.id),label:project.name}))??[])]}/><Field label="Shared from (UTC)" hint="Historical widgets only."><input className={inputClass} type="datetime-local" value={from.slice(0,16)} onChange={event=>{setFrom(event.target.value?`${event.target.value}:00.000Z`:'');if(editing)setDirty(true);}}/></Field><Field label="Shared to (UTC)"><input className={inputClass} type="datetime-local" value={to.slice(0,16)} onChange={event=>{setTo(event.target.value?`${event.target.value}:00.000Z`:'');if(editing)setDirty(true);}}/></Field></div><p className="mt-3 text-xs text-slate-500">Current snapshot widgets show today’s inventory. Widget filters narrow the shared scope; time overrides are labeled on each widget. Refresh applies changed query filters.</p>
      {editing&&<div className="mt-5 flex flex-wrap items-end gap-3"><div className="min-w-64 flex-1"><Select label="Add a saved view" value={viewId} onChange={setViewId} options={[{value:'',label:'Choose a view'},...views.map(view=>({value:view.id,label:view.name}))]}/></div><Button type="button" disabled={!viewId||widgets.length>=10} onClick={()=>{const view=views.find(item=>item.id===viewId);if(!view)return;const source=structuredClone(view.definition.metrics[0]);change([...widgets,{...source,id:createClientId(),title:view.name,view:{...source.view,scope:{...view.scope,...view.definition.scope,...source.view?.scope},from:source.view?.from??view.definition.from,to:source.view?.to??view.definition.to,timezone:source.view?.timezone??view.definition.timezone},layout:{width:6,height:'regular'}}]);}}>Add widget</Button><Link href="/telemetry?tab=analyze" className="py-2 text-sm text-amber-300 hover:underline">Create a saved view →</Link></div>}
      {dirty&&<p role="status" className="mt-3 text-xs text-amber-200">Unsaved changes. Save or cancel before switching dashboards.</p>}</Card>
      {!widgets.length&&<p className="rounded-xl border border-dashed border-slate-700 p-12 text-center text-sm text-slate-400">Add a saved metric view to start your dashboard. Up to 10 widgets can be arranged and resized.</p>}
      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={({active,over})=>{if(over&&active.id!==over.id)change(moveTelemetryWidget(widgets,widgets.findIndex(widget=>widget.id===active.id),widgets.findIndex(widget=>widget.id===over.id)));}}><SortableContext items={widgets.map(widget=>widget.id!)} strategy={rectSortingStrategy}><div data-dashboard-grid className="grid items-start gap-4 lg:grid-cols-12">{widgets.map((widget,index)=><MetricDashboardWidget key={widget.id} widget={widget} metrics={metrics} catalog={catalog} scope={scope} window={{from:from||undefined,to:to||undefined,timezone:'UTC'}} refresh={refresh} editing={editing} onChange={next=>change(widgets.map(item=>item.id===widget.id?next:item))} reportId={dirty?undefined:current?.id} onDuplicate={()=>change([...widgets,{...structuredClone(widget),id:createClientId(),title:`${widget.title??'Widget'} copy`}])} onRemove={()=>change(widgets.filter(item=>item.id!==widget.id))} onMove={delta=>change(moveTelemetryWidget(widgets,index,index+delta))} index={index} count={widgets.length}/>)}</div></SortableContext></DndContext>
    </>}
  </div>{selected==='overview'&&<OperationalDashboard/>}</div>;
}
