import { Pool } from 'pg';
import { PostgresAdapter } from './PostgresAdapter';
import { runDbContractTests } from './contract';

/**
 * Runs the shared Db contract against a real PostgreSQL server.
 *
 * Skipped unless AGENT_HQ_TEST_PG_URL is set, so the default suite stays runnable with no
 * external services. CI sets it; see docs/postgres-migration-plan.md.
 *
 * Each test gets its own schema rather than its own database: creating a database per
 * test is slow and cannot run concurrently, while a schema is cheap and gives the same
 * isolation via search_path.
 */
const PG_URL = process.env.AGENT_HQ_TEST_PG_URL;
const describeOrSkip = PG_URL ? describe : describe.skip;

describeOrSkip('PostgreSQL adapter', () => {
  let counter = 0;

  runDbContractTests({
    name: 'PostgresAdapter',
    setup: async () => {
      const schema = `adapter_test_${process.pid}_${counter++}`;
      const pool = new Pool({ connectionString: PG_URL });

      // Bind every pooled connection to this test's schema. It must be applied on
      // connect, not once up front: the pool opens connections lazily, and a connection
      // created later would otherwise default to the public schema.
      pool.on('connect', (client) => { void client.query(`SET search_path TO ${schema}`); });

      const admin = await pool.connect();
      await admin.query(`CREATE SCHEMA IF NOT EXISTS ${schema}`);
      await admin.query(`SET search_path TO ${schema}`);
      await admin.query(`
        CREATE TABLE parents (
          id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL
        );
        CREATE TABLE children (
          id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          parent_id bigint NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
          label     text
        );
      `);
      admin.release();

      return {
        db: new PostgresAdapter(pool),
        cleanup: async () => {
          try {
            const client = await pool.connect();
            await client.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
            client.release();
          } catch { /* pool may already be closed */ }
          await pool.end().catch(() => undefined);
        },
      };
    },
  });
});
