-- Agent HQ PostgreSQL baseline migration
--
-- This is the frozen PostgreSQL schema captured at the engine cutover. It is migration 00,
-- not a generated sidecar: future schema changes belong in new numbered migrations.
-- Statement order is deliberate: tables first, then indexes, then foreign keys.
-- schema_migrations is intentionally absent; the migration runner owns that ledger.

-- === BASELINE SECTION: tables ===
CREATE TABLE agent_mcp_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  mcp_server_id bigint NOT NULL,
  overrides text NOT NULL DEFAULT '{}',
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE agent_mcp_capability_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  capability_key text NOT NULL,
  enabled bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE agent_tool_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  tool_id bigint NOT NULL,
  overrides text NOT NULL DEFAULT '{}',
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE agents (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  role text NOT NULL DEFAULT '',
  session_key text NOT NULL,
  workspace_path text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'idle' CHECK (status IN ('idle','running','blocked')),
  last_active text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  openclaw_agent_id text,
  model text,
  runtime_type text NOT NULL DEFAULT 'openclaw',
  runtime_config text,
  hooks_url text,
  preferred_provider text NOT NULL DEFAULT 'anthropic',
  slug text,
  os_user text,
  repo_path text,
  hooks_auth_header text,
  job_title text NOT NULL DEFAULT '',
  project_id bigint,
  sprint_id bigint,
  schedule text NOT NULL DEFAULT '',
  dispatch_mode text NOT NULL DEFAULT 'agentTurn',
  job_instructions text NOT NULL DEFAULT '',
  skill_name text,
  skill_names text NOT NULL DEFAULT '[]',
  enabled bigint NOT NULL DEFAULT 1,
  timeout_seconds bigint NOT NULL DEFAULT 900,
  github_identity_id bigint,
  stall_threshold_min bigint NOT NULL DEFAULT 30,
  max_retries bigint NOT NULL DEFAULT 3,
  sort_rules text NOT NULL DEFAULT '[]',
  startup_grace_seconds bigint,
  heartbeat_stale_seconds bigint,
  instructions_version bigint NOT NULL DEFAULT 0,
  system_role text,
  repo_url text,
  repo_access_mode text CHECK (repo_access_mode IN ('worktree','clone')),
  deleted_at text,
  job_instructions_updated_at text,
  tenant_id bigint,
  global_mcp_admin bigint NOT NULL DEFAULT 0,
  provider_connection_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE app_settings (
  key text,
  value text NOT NULL DEFAULT '',
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (key)
);

CREATE TABLE canonical_chat_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  channel text NOT NULL,
  session_key text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE chat_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  instance_id bigint,
  agent_id bigint,
  filename text NOT NULL,
  filepath text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size bigint NOT NULL DEFAULT 0,
  uploaded_by text NOT NULL DEFAULT 'user',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE chat_messages (
  id text,
  agent_id bigint NOT NULL,
  role text NOT NULL CHECK (role IN ('user','assistant','system','tool')),
  content text NOT NULL DEFAULT '',
  timestamp text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  session_key text NOT NULL DEFAULT '',
  instance_id bigint,
  event_type text NOT NULL DEFAULT 'text',
  event_meta text NOT NULL DEFAULT '{}',
  durable_run_id text,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE default_package_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  package_key text NOT NULL,
  package_version bigint NOT NULL,
  applied_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  mode text NOT NULL DEFAULT 'install',
  created_json text NOT NULL DEFAULT '{}',
  restored_json text NOT NULL DEFAULT '{}',
  updated_json text NOT NULL DEFAULT '{}',
  conflicts_json text NOT NULL DEFAULT '[]',
  PRIMARY KEY (id)
);

CREATE TABLE dev_db_sync_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  actor text NOT NULL,
  source_kind text NOT NULL,
  source_db_path text NOT NULL,
  target_environment_id text NOT NULL,
  target_db_path text NOT NULL,
  scope text NOT NULL,
  requested_task_id bigint NOT NULL,
  task_id bigint,
  synced_task_ids_json text NOT NULL,
  row_counts_json text NOT NULL,
  dry_run bigint NOT NULL DEFAULT 0,
  reason text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE dispatch_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint,
  dispatched_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  routing_reason text,
  candidate_count bigint,
  candidates_skipped text,
  agent_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE external_event_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint,
  source text,
  event_name text NOT NULL,
  task_type text,
  status_includes_json text NOT NULL DEFAULT '[]',
  status_excludes_json text NOT NULL DEFAULT '[]',
  action_kind text NOT NULL DEFAULT 'ignore',
  action_target text,
  apply_review_evidence bigint NOT NULL DEFAULT 0,
  apply_failure_detail bigint NOT NULL DEFAULT 0,
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  sprint_id bigint,
  sprint_type text,
  PRIMARY KEY (id)
);

CREATE TABLE external_task_event_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  fingerprint text NOT NULL,
  source text NOT NULL,
  event text NOT NULL,
  task_id bigint NOT NULL,
  environment_id text NOT NULL,
  queue_id text NOT NULL,
  lease_id text NOT NULL,
  branch text,
  commit_sha text,
  review_url text,
  message text NOT NULL,
  payload_json text NOT NULL,
  received_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  processed_at text,
  processing_state text NOT NULL DEFAULT 'received',
  processing_error text,
  mapping_id bigint,
  mapping_action_kind text,
  mapping_action_target text,
  request_metadata_json text,
  PRIMARY KEY (id)
);

CREATE TABLE github_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint,
  github_username text NOT NULL,
  token text NOT NULL DEFAULT '',
  git_author_name text NOT NULL DEFAULT '',
  git_author_email text NOT NULL DEFAULT '',
  lane text NOT NULL DEFAULT 'shared' CHECK (lane IN ('dev','qa','release','shared')),
  notes text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  last_validated_at text,
  validation_status text CHECK (validation_status IN (NULL,'valid','failed')),
  validation_error text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE instance_artifacts (
  instance_id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint,
  current_stage text NOT NULL DEFAULT 'dispatch' CHECK (current_stage IN ('dispatch','start','heartbeat','progress','blocker','completion')),
  summary text,
  latest_commit_hash text,
  branch_name text,
  changed_files_json text NOT NULL DEFAULT '[]',
  changed_files_count bigint,
  blocker_reason text,
  outcome text,
  last_agent_heartbeat_at text,
  last_meaningful_output_at text,
  started_at text,
  completed_at text,
  stale bigint NOT NULL DEFAULT 0,
  stale_at text,
  session_key text,
  last_note_at text,
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (instance_id)
);

CREATE TABLE integrity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  agent_id bigint,
  instance_id bigint,
  anomaly_type text NOT NULL CHECK (anomaly_type IN (
          'missing_review_evidence',
          'missing_qa_evidence',
          'commit_mismatch',
          'deployed_not_verified',
          'stale_outcome_write',
          'branch_missing_on_origin',
          'evidence_placeholder'
        )),
  detail text,
  resolved bigint NOT NULL DEFAULT 0,
  resolved_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE job_instances (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  task_id bigint,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','dispatched','running','done','failed','cancelled')),
  session_key text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  dispatched_at text,
  completed_at text,
  error text,
  artifact_summary text,
  run_stage text,
  last_heartbeat_at text,
  last_meaningful_output_at text,
  latest_commit_hash text,
  branch_name text,
  changed_files text,
  changed_files_count bigint,
  started_at text,
  blocker_reason text,
  abort_attempted_at text,
  abort_status text,
  abort_error text,
  task_outcome text,
  token_input bigint,
  token_output bigint,
  token_total bigint,
  effective_model text,
  payload_sent text,
  response text,
  run_id text,
  last_agent_heartbeat_at text,
  worktree_path text,
  failure_class text,
  failure_stage text,
  runtime_ended_at text,
  runtime_end_success bigint,
  runtime_end_error text,
  runtime_end_source text,
  lifecycle_outcome_posted_at text,
  effective_thinking_level text,
  runtime_completed_at text,
  lifecycle_handoff_status text,
  semantic_outcome_missing bigint NOT NULL DEFAULT 0,
  durable_run_id text,
  effective_fast_mode bigint CHECK (effective_fast_mode IN (0, 1)),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE lifecycle_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_type text,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  instance_id bigint,
  agent_id bigint,
  job_title text NOT NULL DEFAULT '',
  level text NOT NULL DEFAULT 'info' CHECK (level IN ('info','warn','error','debug')),
  message text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE mcp_api_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  name text NOT NULL DEFAULT '',
  key_prefix text NOT NULL DEFAULT '',
  key_hash text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_used_at text,
  revoked_at text,
  tenant_id bigint,
  global_admin bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE mcp_servers (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL DEFAULT '',
  transport text NOT NULL DEFAULT 'stdio' CHECK (transport IN ('stdio')),
  command text NOT NULL,
  args text NOT NULL DEFAULT '[]',
  env text NOT NULL DEFAULT '{}',
  cwd text,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE notification_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  source text,
  outlet text,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE openclaw_transcript_ingest_state (
  instance_id bigint GENERATED BY DEFAULT AS IDENTITY,
  session_file text NOT NULL,
  last_line_index bigint NOT NULL DEFAULT 0,
  last_event_at text,
  last_heartbeat_at text,
  last_meaningful_output_at text,
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (instance_id)
);

CREATE TABLE project_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  entity_type text NOT NULL CHECK (entity_type IN ('project', 'sprint', 'job_template')),
  entity_id bigint NOT NULL,
  action text NOT NULL CHECK (action IN ('created', 'updated', 'deleted')),
  actor text NOT NULL DEFAULT 'system',
  changes text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE project_file_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint NOT NULL,
  file_id bigint NOT NULL,
  version_number bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  created_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  change_source text NOT NULL DEFAULT 'api',
  PRIMARY KEY (id)
);

CREATE TABLE project_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  uploaded_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by text NOT NULL DEFAULT 'manual',
  updated_at text NOT NULL DEFAULT '',
  current_version bigint NOT NULL DEFAULT 1,
  current_version_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  context_md text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  repo_path text,
  repo_url text,
  repo_access_mode text CHECK (repo_access_mode IN ('worktree','clone')),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE provider_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint,
  slug text NOT NULL CHECK (slug IN ('anthropic','openai','google','openrouter','ollama','openai-codex','mlx-studio','minimax')),
  display_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','connected','failed')),
  config text NOT NULL DEFAULT '{}',
  last_validated_at text,
  validation_error text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE provider_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  provider_slug text NOT NULL,
  auth_mode text NOT NULL,
  runtime_type text NOT NULL,
  external_ref text NOT NULL,
  display_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','connected','failed')),
  metadata text NOT NULL DEFAULT '{}',
  last_validated_at text,
  validation_error text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE recurring_task_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  series_id bigint NOT NULL,
  scheduled_for text NOT NULL,
  created_task_id bigint,
  status text NOT NULL CHECK (status IN ('started','created','skipped','failed')),
  error_message text,
  started_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  finished_at text,
  idempotency_key text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE recurring_task_series (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  sprint_id bigint NOT NULL,
  title_template text NOT NULL,
  description_template text NOT NULL DEFAULT '',
  task_type text NOT NULL,
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
  story_points bigint NOT NULL,
  status_on_create text NOT NULL CHECK (status_on_create IN ('todo','ready','in_progress','dev_deploy_queued','dev_deploying','review','qa_pass','ready_to_merge','deployed','done','needs_attention','cancelled','stalled','failed','blocked')),
  schedule_expression text NOT NULL,
  timezone text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  next_run_at text,
  last_run_at text,
  overlap_policy text NOT NULL DEFAULT 'skip_if_active' CHECK (overlap_policy IN ('skip_if_active','create_anyway')),
  agent_id bigint,
  created_by text NOT NULL DEFAULT 'system',
  updated_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE routing_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE routing_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  lane text NOT NULL DEFAULT 'default',
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  task_type text,
  priority bigint NOT NULL DEFAULT 0,
  is_protected bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE security_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  event_type text NOT NULL DEFAULT 'workspace_boundary_violation',
  agent_id bigint,
  instance_id bigint,
  task_id bigint,
  details text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE session_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  session_id bigint NOT NULL,
  ordinal bigint NOT NULL,
  role text NOT NULL CHECK (role IN ('user','assistant','system','tool')),
  event_type text NOT NULL DEFAULT 'text',
  content text NOT NULL DEFAULT '',
  event_meta text NOT NULL DEFAULT '{}',
  raw_payload text,
  timestamp text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  external_key text NOT NULL,
  runtime text NOT NULL,
  agent_id bigint,
  task_id bigint,
  instance_id bigint,
  project_id bigint,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','failed','abandoned')),
  title text NOT NULL DEFAULT '',
  started_at text,
  ended_at text,
  message_count bigint NOT NULL DEFAULT 0,
  token_input bigint,
  token_output bigint,
  metadata text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL DEFAULT 1,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT 'atlas' CHECK (source IN ('atlas','workspace','system')),
  fs_path text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_routing_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint,
  project_id bigint,
  sprint_type text,
  task_type text,
  status text NOT NULL,
  agent_id bigint,
  priority bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint NOT NULL,
  status_key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  terminal bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  allowed_transitions_json text NOT NULL DEFAULT '[]',
  stage_order bigint NOT NULL DEFAULT 0,
  is_default_entry bigint NOT NULL DEFAULT 0,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_transition_requirement_tombstones (
  sprint_id bigint NOT NULL,
  task_type_key text NOT NULL DEFAULT '',
  outcome text NOT NULL,
  field_name text NOT NULL,
  requirement_type text NOT NULL,
  match_field_key text NOT NULL DEFAULT '',
  deleted_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (sprint_id, task_type_key, outcome, field_name, requirement_type, match_field_key)
);

CREATE TABLE sprint_task_transition_requirements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint,
  project_id bigint,
  sprint_type text,
  task_type text,
  outcome text NOT NULL,
  field_name text NOT NULL,
  requirement_type text NOT NULL DEFAULT 'required' CHECK (requirement_type IN ('required','match','from_status')),
  match_field text,
  severity text NOT NULL DEFAULT 'block' CHECK (severity IN ('block','warn')),
  message text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint,
  project_id bigint,
  sprint_type text,
  task_type text,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  is_protected bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_outcomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  task_type text,
  outcome_key text NOT NULL,
  label text NOT NULL,
  description text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  behavior text NOT NULL DEFAULT 'base' CHECK (behavior IN ('base','extend','override','disable')),
  badge_variant text,
  stage_order bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 1,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_relationship_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  key text NOT NULL,
  label text NOT NULL,
  inverse_label text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'informational',
  affects_dispatch_eligibility bigint NOT NULL DEFAULT 0,
  direction_semantics text NOT NULL DEFAULT 'informational' CHECK (direction_semantics IN ('target_blocks_source','source_blocks_target','informational')),
  active_statuses_json text NOT NULL DEFAULT '[]',
  resolved_statuses_json text NOT NULL DEFAULT '[]',
  allow_create_related_task bigint NOT NULL DEFAULT 0,
  default_related_task_type text,
  default_related_task_status text,
  is_system bigint NOT NULL DEFAULT 1,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_task_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  status_key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  terminal bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  allowed_transitions_json text NOT NULL DEFAULT '[]',
  stage_order bigint NOT NULL DEFAULT 0,
  is_default_entry bigint NOT NULL DEFAULT 0,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_task_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  task_type text NOT NULL,
  is_system bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  key text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  is_system bigint NOT NULL DEFAULT 1,
  status_seeded_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  repo_required bigint NOT NULL DEFAULT 0,
  project_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_workflow_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  template_id bigint NOT NULL,
  status_key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  stage_order bigint NOT NULL DEFAULT 0,
  terminal bigint NOT NULL DEFAULT 0,
  is_default_entry bigint NOT NULL DEFAULT 0,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_workflow_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  key text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  is_default bigint NOT NULL DEFAULT 1,
  is_system bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_workflow_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  template_id bigint NOT NULL,
  from_status_key text NOT NULL,
  to_status_key text NOT NULL,
  transition_key text NOT NULL,
  label text NOT NULL,
  outcome text,
  stage_order bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 1,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprints (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  name text NOT NULL,
  goal text NOT NULL DEFAULT '',
  sprint_type text NOT NULL DEFAULT 'generic',
  workflow_template_key text,
  status text NOT NULL DEFAULT 'planning' CHECK (status IN ('planning','active','paused','complete','closed')),
  length_kind text NOT NULL DEFAULT 'time' CHECK (length_kind IN ('time','runs')),
  length_value text NOT NULL DEFAULT '',
  started_at text,
  ended_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  task_policy_seeded_at text,
  tenant_id bigint,
  repo_path text,
  repo_url text,
  repo_access_mode text CHECK (repo_access_mode IN ('worktree','clone')),
  PRIMARY KEY (id)
);

CREATE TABLE story_point_model_routing (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  max_points bigint NOT NULL,
  provider text,
  model text NOT NULL,
  fallback_model text,
  max_turns bigint,
  max_budget_usd double precision,
  label text,
  created_at text DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  thinking_level text,
  project_id bigint,
  sprint_id bigint,
  sprint_type text,
  fast_mode bigint CHECK (fast_mode IN (0, 1)),
  tenant_id bigint,
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE system_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  policy_key text NOT NULL,
  from_status text NOT NULL,
  to_status text NOT NULL,
  trigger_event text NOT NULL,
  classification text NOT NULL DEFAULT 'configurable',
  enabled bigint NOT NULL DEFAULT 1,
  threshold_seconds bigint,
  description text NOT NULL DEFAULT '',
  source_file text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  filename text NOT NULL,
  filepath text NOT NULL,
  mime_type text NOT NULL DEFAULT '',
  size bigint NOT NULL DEFAULT 0,
  uploaded_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_creation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  sprint_id bigint,
  job_id bigint,
  source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','skill','agent','api','import')),
  routing text NOT NULL DEFAULT '',
  confidence text NOT NULL DEFAULT '' CHECK (confidence IN ('','low','medium','high')),
  scope_size text NOT NULL DEFAULT '' CHECK (scope_size IN ('','xs','small','medium','large','xl')),
  assumptions text NOT NULL DEFAULT '',
  open_questions text NOT NULL DEFAULT '',
  needs_split bigint NOT NULL DEFAULT 0,
  expected_artifact text NOT NULL DEFAULT '',
  success_mode text NOT NULL DEFAULT '',
  raw_input text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  agent_id bigint,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_dependencies (
  blocker_id bigint NOT NULL,
  blocked_id bigint NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  sprint_id bigint,
  agent_id bigint,
  from_status text,
  to_status text NOT NULL,
  moved_by text NOT NULL DEFAULT 'system',
  move_type text NOT NULL DEFAULT 'automatic' CHECK (move_type IN ('automatic','outcome','manual','rescue','dispatch')),
  instance_id bigint,
  reason text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_field_schemas (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  task_type text,
  schema_json text NOT NULL DEFAULT '{}',
  is_system bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  changed_by text NOT NULL DEFAULT 'system',
  field text NOT NULL,
  old_value text,
  new_value text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  author text NOT NULL DEFAULT 'system',
  content text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_outcome_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  sprint_id bigint,
  job_id bigint,
  first_pass_qa bigint NOT NULL DEFAULT 0,
  reopened_count bigint NOT NULL DEFAULT 0,
  rerouted_count bigint NOT NULL DEFAULT 0,
  split_after_creation bigint NOT NULL DEFAULT 0,
  blocked_after_creation bigint NOT NULL DEFAULT 0,
  clarification_count bigint NOT NULL DEFAULT 0,
  notes_count bigint NOT NULL DEFAULT 0,
  cycle_time_hours double precision,
  outcome_quality text NOT NULL DEFAULT '' CHECK (outcome_quality IN ('','good','acceptable','poor')),
  failure_reasons text NOT NULL DEFAULT '[]',
  outcome_summary text NOT NULL DEFAULT '',
  recorded_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  agent_id bigint,
  spawned_defects bigint NOT NULL DEFAULT 0,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  source_task_id bigint NOT NULL,
  target_task_id bigint NOT NULL,
  relationship_type_key text NOT NULL,
  metadata_json text NOT NULL DEFAULT '{}',
  created_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CHECK (source_task_id != target_task_id)
);

CREATE TABLE task_statuses (
  name text,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  terminal bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  allowed_transitions text NOT NULL DEFAULT '[]',
  PRIMARY KEY (name)
);

CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'todo',
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
  project_id bigint,
  agent_id bigint,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  active_instance_id bigint,
  recurring bigint NOT NULL DEFAULT 0,
  sprint_id bigint NOT NULL,
  branch_url text,
  retry_count bigint NOT NULL DEFAULT 0,
  max_retries bigint NOT NULL DEFAULT 3,
  dispatched_at text,
  claimed_at text,
  routing_reason text,
  task_type text,
  story_points bigint,
  origin_task_id bigint,
  defect_type text,
  failure_class text,
  failure_detail text,
  review_owner_agent_id bigint,
  paused_at text,
  pause_reason text,
  first_dispatched_at text,
  total_dispatch_count bigint NOT NULL DEFAULT 0,
  manual_intervention_count bigint NOT NULL DEFAULT 0,
  previous_status text,
  custom_fields_json text NOT NULL DEFAULT '{}',
  recurring_series_id bigint,
  scheduled_for text,
  schedule_run_id bigint,
  generated_from text,
  assigned_agent_id bigint,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE telemetry_schema_config (
  id bigint DEFAULT 1,
  fields text NOT NULL DEFAULT '[]',
  description text NOT NULL DEFAULT '',
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE tenants (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  slug text NOT NULL,
  is_default bigint NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE tools (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL DEFAULT 1,
  name text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL DEFAULT '',
  implementation_type text NOT NULL DEFAULT 'bash' CHECK (implementation_type IN ('bash','shell','script','mcp','function','http')),
  implementation_body text NOT NULL DEFAULT '',
  input_schema text NOT NULL DEFAULT '{}',
  permissions text NOT NULL DEFAULT 'read_only' CHECK (permissions IN ('read_only','read_write','exec','network')),
  tags text NOT NULL DEFAULT '[]',
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE transition_requirements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_type text,
  outcome text NOT NULL,
  field_name text NOT NULL,
  requirement_type text NOT NULL DEFAULT 'required' CHECK (requirement_type IN ('required','match','from_status')),
  match_field text,
  severity text NOT NULL DEFAULT 'block' CHECK (severity IN ('block','warn')),
  message text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE workflow_file_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint NOT NULL,
  workflow_id bigint NOT NULL,
  file_id bigint NOT NULL,
  version_number bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  created_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  change_source text NOT NULL DEFAULT 'api',
  PRIMARY KEY (id)
);

CREATE TABLE workflow_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint NOT NULL,
  workflow_id bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  uploaded_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by text NOT NULL DEFAULT 'manual',
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  current_version bigint NOT NULL DEFAULT 1,
  current_version_id bigint,
  PRIMARY KEY (id)
);

-- === BASELINE SECTION: indexes ===
CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_mcp_assignments_agent_id_mcp_server_id ON agent_mcp_assignments (agent_id, mcp_server_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_mcp_capability_policies_agent_id_capability_key ON agent_mcp_capability_policies (agent_id, capability_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_tool_assignments_agent_id_tool_id ON agent_tool_assignments (agent_id, tool_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_session_key ON agents (session_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_chat_sessions_agent_id_channel ON canonical_chat_sessions (agent_id, channel);
CREATE UNIQUE INDEX IF NOT EXISTS uq_external_task_event_receipts_fingerprint ON external_task_event_receipts (fingerprint);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_api_keys_key_hash ON mcp_api_keys (key_hash);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_tenant_id_slug ON mcp_servers (tenant_id, slug);
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_file_versions_file_id_version_number ON project_file_versions (file_id, version_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_provider_connections_tenant_id_runtime_type_provider_slug_auth_mode_external_ref ON provider_connections (tenant_id, runtime_type, provider_slug, auth_mode, external_ref);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recurring_task_runs_idempotency_key ON recurring_task_runs (idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recurring_task_runs_series_id_scheduled_for ON recurring_task_runs (series_id, scheduled_for);
CREATE UNIQUE INDEX IF NOT EXISTS uq_session_messages_session_id_ordinal ON session_messages (session_id, ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sessions_external_key ON sessions (external_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_skills_tenant_id_name ON skills (tenant_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_task_statuses_sprint_id_status_key ON sprint_task_statuses (sprint_id, status_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_type_outcomes_tenant_id_sprint_type_key_task_type_outcome_key ON sprint_type_outcomes (tenant_id, sprint_type_key, task_type, outcome_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_type_relationship_types_tenant_id_sprint_type_key_key ON sprint_type_relationship_types (tenant_id, sprint_type_key, key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_type_task_statuses_tenant_id_sprint_type_key_status_key ON sprint_type_task_statuses (tenant_id, sprint_type_key, status_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_type_task_types_tenant_id_sprint_type_key_task_type ON sprint_type_task_types (tenant_id, sprint_type_key, task_type);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_types_tenant_id_key ON sprint_types (tenant_id, key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_workflow_statuses_template_id_status_key ON sprint_workflow_statuses (template_id, status_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_workflow_templates_tenant_id_sprint_type_key_key ON sprint_workflow_templates (tenant_id, sprint_type_key, key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_workflow_transitions_template_id_from_status_key_to_status_key ON sprint_workflow_transitions (template_id, from_status_key, to_status_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sprint_workflow_transitions_template_id_transition_key ON sprint_workflow_transitions (template_id, transition_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_system_policies_policy_key ON system_policies (policy_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_task_field_schemas_tenant_id_sprint_type_key_task_type ON task_field_schemas (tenant_id, sprint_type_key, task_type);
CREATE UNIQUE INDEX IF NOT EXISTS uq_task_outcome_metrics_task_id ON task_outcome_metrics (task_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_task_relationships_source_task_id_target_task_id_relationship_type_key ON task_relationships (source_task_id, target_task_id, relationship_type_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenants_slug ON tenants (slug);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tools_tenant_id_slug ON tools (tenant_id, slug);
CREATE UNIQUE INDEX IF NOT EXISTS uq_workflow_file_versions_file_id_version_number ON workflow_file_versions (file_id, version_number);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_assignments_agent ON agent_mcp_assignments(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_assignments_server ON agent_mcp_assignments(mcp_server_id);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_capability_policies_agent ON agent_mcp_capability_policies(agent_id);
CREATE INDEX IF NOT EXISTS idx_agents_provider_connection ON agents(provider_connection_id);
CREATE INDEX IF NOT EXISTS idx_agents_tenant ON agents(tenant_id);
CREATE INDEX IF NOT EXISTS idx_ata_agent ON agent_tool_assignments(agent_id);
CREATE INDEX IF NOT EXISTS idx_ata_tool ON agent_tool_assignments(tool_id);
CREATE INDEX IF NOT EXISTS idx_canonical_chat_sessions_agent_channel ON canonical_chat_sessions(agent_id, channel);
CREATE INDEX IF NOT EXISTS idx_chat_attachments_instance ON chat_attachments(instance_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_agent ON chat_messages(agent_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_agent_durable_instance_session_ts ON chat_messages(agent_id, durable_run_id, instance_id, session_key, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_agent_instance_session_ts ON chat_messages(agent_id, instance_id, session_key, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_agent_instance_ts ON chat_messages(agent_id, instance_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_agent_session_ts ON chat_messages(agent_id, session_key, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_durable_run ON chat_messages(durable_run_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_instance ON chat_messages(instance_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_instance_ts ON chat_messages(instance_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_key_ts ON chat_messages(session_key, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_tenant ON chat_messages(tenant_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_timestamp ON chat_messages(timestamp);
CREATE INDEX IF NOT EXISTS idx_default_package_applications_tenant ON default_package_applications(tenant_id, package_key, package_version);
CREATE INDEX IF NOT EXISTS idx_dev_db_sync_audit_environment ON dev_db_sync_audit(target_environment_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dev_db_sync_audit_requested_task ON dev_db_sync_audit(requested_task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dev_db_sync_audit_task ON dev_db_sync_audit(task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dispatch_log_agent ON dispatch_log(agent_id);
CREATE INDEX IF NOT EXISTS idx_dispatch_log_dispatched_at ON dispatch_log(dispatched_at);
CREATE INDEX IF NOT EXISTS idx_dispatch_log_task ON dispatch_log(task_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_external_event_mappings_effective_unique_tenant ON external_event_mappings( COALESCE(tenant_id, 0), COALESCE(project_id, 0), COALESCE(source, ''), event_name, COALESCE(task_type, ''), status_includes_json, status_excludes_json, action_kind, COALESCE(action_target, ''), apply_review_evidence, apply_failure_detail, enabled, priority );
CREATE INDEX IF NOT EXISTS idx_external_event_mappings_lookup ON external_event_mappings(event_name, source, project_id, task_type, enabled, priority);
CREATE INDEX IF NOT EXISTS idx_external_event_mappings_scope_lookup ON external_event_mappings(project_id, sprint_type, sprint_id, event_name, source, task_type, enabled, priority);
CREATE INDEX IF NOT EXISTS idx_external_event_mappings_tenant ON external_event_mappings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_external_task_event_receipts_lease ON external_task_event_receipts(lease_id);
CREATE INDEX IF NOT EXISTS idx_external_task_event_receipts_processing_state ON external_task_event_receipts(processing_state);
CREATE INDEX IF NOT EXISTS idx_external_task_event_receipts_source_event ON external_task_event_receipts(source, event);
CREATE INDEX IF NOT EXISTS idx_external_task_event_receipts_task ON external_task_event_receipts(task_id);
CREATE INDEX IF NOT EXISTS idx_github_identities_enabled ON github_identities(enabled);
CREATE INDEX IF NOT EXISTS idx_github_identities_lane ON github_identities(lane);
CREATE INDEX IF NOT EXISTS idx_github_identities_tenant ON github_identities(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_github_identities_tenant_username ON github_identities(tenant_id, github_username);
CREATE INDEX IF NOT EXISTS idx_github_identities_username ON github_identities(github_username);
CREATE INDEX IF NOT EXISTS idx_instance_artifacts_stale ON instance_artifacts(stale, updated_at);
CREATE INDEX IF NOT EXISTS idx_instance_artifacts_task ON instance_artifacts(task_id);
CREATE INDEX IF NOT EXISTS idx_instances_agent ON job_instances(agent_id);
CREATE INDEX IF NOT EXISTS idx_instances_status ON job_instances(status);
CREATE INDEX IF NOT EXISTS idx_instances_task ON job_instances(task_id);
CREATE INDEX IF NOT EXISTS idx_integrity_events_agent ON integrity_events(agent_id);
CREATE INDEX IF NOT EXISTS idx_integrity_events_anomaly_type ON integrity_events(anomaly_type);
CREATE INDEX IF NOT EXISTS idx_integrity_events_created ON integrity_events(created_at);
CREATE INDEX IF NOT EXISTS idx_integrity_events_project ON integrity_events(project_id);
CREATE INDEX IF NOT EXISTS idx_integrity_events_resolved ON integrity_events(resolved);
CREATE INDEX IF NOT EXISTS idx_integrity_events_task ON integrity_events(task_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_instances_durable_run_id ON job_instances(durable_run_id) WHERE durable_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_job_instances_tenant ON job_instances(tenant_id);
CREATE INDEX IF NOT EXISTS idx_lifecycle_rules_lookup ON lifecycle_rules(task_type, from_status, outcome);
CREATE INDEX IF NOT EXISTS idx_lifecycle_rules_type ON lifecycle_rules(task_type);
CREATE INDEX IF NOT EXISTS idx_logs_agent ON logs(agent_id);
CREATE INDEX IF NOT EXISTS idx_logs_created ON logs(created_at);
CREATE INDEX IF NOT EXISTS idx_logs_instance ON logs(instance_id);
CREATE INDEX IF NOT EXISTS idx_logs_tenant ON logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mcp_api_keys_agent ON mcp_api_keys(agent_id);
CREATE INDEX IF NOT EXISTS idx_mcp_api_keys_enabled ON mcp_api_keys(enabled);
CREATE INDEX IF NOT EXISTS idx_mcp_api_keys_global_admin ON mcp_api_keys(global_admin);
CREATE INDEX IF NOT EXISTS idx_mcp_api_keys_tenant ON mcp_api_keys(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_enabled ON mcp_servers(enabled);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_slug ON mcp_servers(slug);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_tenant ON mcp_servers(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mcp_servers_tenant_slug ON mcp_servers(tenant_id, slug);
CREATE INDEX IF NOT EXISTS idx_notification_records_tenant_created ON notification_records(tenant_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_project_audit_log_created ON project_audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_project_audit_log_entity ON project_audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_project_audit_log_project ON project_audit_log(project_id);
CREATE INDEX IF NOT EXISTS idx_project_file_versions_file ON project_file_versions(file_id, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_project_file_versions_tenant_project ON project_file_versions(tenant_id, project_id, file_id);
CREATE INDEX IF NOT EXISTS idx_project_files_project ON project_files(project_id);
CREATE INDEX IF NOT EXISTS idx_projects_tenant ON projects(tenant_id);
CREATE INDEX IF NOT EXISTS idx_provider_config_slug ON provider_config(slug);
CREATE INDEX IF NOT EXISTS idx_provider_config_status ON provider_config(status);
CREATE INDEX IF NOT EXISTS idx_provider_config_tenant ON provider_config(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_config_tenant_slug ON provider_config(tenant_id, slug);
CREATE INDEX IF NOT EXISTS idx_provider_connections_lookup ON provider_connections(tenant_id, runtime_type, provider_slug, status);
CREATE INDEX IF NOT EXISTS idx_provider_connections_tenant ON provider_connections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_recurring_task_runs_created_task ON recurring_task_runs(created_task_id) WHERE created_task_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_recurring_task_runs_series_history ON recurring_task_runs(series_id, scheduled_for DESC);
CREATE INDEX IF NOT EXISTS idx_recurring_task_series_agent ON recurring_task_series(agent_id) WHERE agent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_recurring_task_series_due ON recurring_task_series(enabled, next_run_at) WHERE enabled = 1 AND next_run_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_recurring_task_series_project ON recurring_task_series(project_id, sprint_id);
CREATE INDEX IF NOT EXISTS idx_recurring_task_series_tenant ON recurring_task_series(tenant_id);
CREATE INDEX IF NOT EXISTS idx_routing_config_from ON routing_config(from_status, outcome);
CREATE INDEX IF NOT EXISTS idx_routing_config_project ON routing_config(project_id);
CREATE INDEX IF NOT EXISTS idx_routing_config_tenant ON routing_config(tenant_id);
CREATE INDEX IF NOT EXISTS idx_routing_transitions_from ON routing_transitions(from_status, outcome);
CREATE INDEX IF NOT EXISTS idx_routing_transitions_project ON routing_transitions(project_id);
CREATE INDEX IF NOT EXISTS idx_routing_transitions_type ON routing_transitions(task_type, from_status, outcome);
CREATE INDEX IF NOT EXISTS idx_rt_from ON routing_transitions(from_status, outcome);
CREATE INDEX IF NOT EXISTS idx_rt_project ON routing_transitions(project_id);
CREATE INDEX IF NOT EXISTS idx_security_events_agent ON security_events(agent_id);
CREATE INDEX IF NOT EXISTS idx_security_events_instance ON security_events(instance_id);
CREATE INDEX IF NOT EXISTS idx_security_events_type ON security_events(event_type, created_at);
CREATE INDEX IF NOT EXISTS idx_session_messages_event_type ON session_messages(event_type);
CREATE INDEX IF NOT EXISTS idx_session_messages_session_ts ON session_messages(session_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_sessions_agent ON sessions(agent_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_agent_project_activity ON sessions(agent_id, project_id, updated_at DESC, ended_at DESC, started_at DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_instance ON sessions(instance_id);
CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_activity ON sessions(project_id, updated_at DESC, ended_at DESC, started_at DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_runtime_status ON sessions(runtime, status, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_task ON sessions(task_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_tenant ON sessions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_skills_name ON skills(name);
CREATE INDEX IF NOT EXISTS idx_skills_source ON skills(source);
CREATE INDEX IF NOT EXISTS idx_skills_tenant ON skills(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_skills_tenant_name ON skills(tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_spmr_provider_points ON story_point_model_routing(provider, max_points);
CREATE INDEX IF NOT EXISTS idx_spmr_scope_points ON story_point_model_routing(project_id, sprint_id, provider, max_points);
CREATE INDEX IF NOT EXISTS idx_sprint_requirement_tombstones_sprint ON sprint_task_transition_requirement_tombstones(sprint_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sprint_task_routing_rules_candidate_unique ON sprint_task_routing_rules( project_id, sprint_type, COALESCE(sprint_id, -1), COALESCE(task_type, ''), status, COALESCE(agent_id, -1), priority ) WHERE project_id IS NOT NULL AND sprint_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sprint_task_routing_rules_lookup ON sprint_task_routing_rules(sprint_id, task_type, status);
CREATE INDEX IF NOT EXISTS idx_sprint_task_routing_rules_scope_lookup ON sprint_task_routing_rules(project_id, sprint_type, sprint_id, task_type, status);
CREATE INDEX IF NOT EXISTS idx_sprint_task_routing_rules_tenant ON sprint_task_routing_rules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sprint_task_statuses_lookup ON sprint_task_statuses(sprint_id, stage_order);
CREATE INDEX IF NOT EXISTS idx_sprint_task_transition_requirements_lookup ON sprint_task_transition_requirements(sprint_id, outcome, task_type);
CREATE INDEX IF NOT EXISTS idx_sprint_task_transition_requirements_scope_lookup ON sprint_task_transition_requirements(project_id, sprint_type, sprint_id, outcome, task_type);
CREATE INDEX IF NOT EXISTS idx_sprint_task_transition_requirements_tenant ON sprint_task_transition_requirements(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sprint_task_transitions_lookup ON sprint_task_transitions(sprint_id, from_status, outcome, task_type);
CREATE INDEX IF NOT EXISTS idx_sprint_task_transitions_scope_lookup ON sprint_task_transitions(project_id, sprint_type, sprint_id, from_status, outcome, task_type);
CREATE INDEX IF NOT EXISTS idx_sprint_task_transitions_tenant ON sprint_task_transitions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sprint_type_outcomes_lookup ON sprint_type_outcomes(tenant_id, sprint_type_key, task_type, enabled, stage_order);
CREATE INDEX IF NOT EXISTS idx_sprint_type_relationship_types_lookup ON sprint_type_relationship_types(tenant_id, sprint_type_key, key);
CREATE INDEX IF NOT EXISTS idx_sprint_type_task_statuses_lookup ON sprint_type_task_statuses(tenant_id, sprint_type_key, status_key);
CREATE INDEX IF NOT EXISTS idx_sprint_type_task_types_lookup ON sprint_type_task_types(tenant_id, sprint_type_key, task_type);
CREATE INDEX IF NOT EXISTS idx_sprint_types_project ON sprint_types(project_id);
CREATE INDEX IF NOT EXISTS idx_sprint_types_system ON sprint_types(is_system);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sprint_types_tenant_key ON sprint_types(tenant_id, key);
CREATE INDEX IF NOT EXISTS idx_sprint_workflow_statuses_template_order ON sprint_workflow_statuses(template_id, stage_order);
CREATE INDEX IF NOT EXISTS idx_sprint_workflow_templates_lookup ON sprint_workflow_templates(tenant_id, sprint_type_key, is_default);
CREATE INDEX IF NOT EXISTS idx_sprint_workflow_transitions_template_from ON sprint_workflow_transitions(template_id, from_status_key, stage_order);
CREATE INDEX IF NOT EXISTS idx_sprints_project ON sprints(project_id);
CREATE INDEX IF NOT EXISTS idx_sprints_status ON sprints(status);
CREATE INDEX IF NOT EXISTS idx_sprints_tenant ON sprints(tenant_id);
CREATE INDEX IF NOT EXISTS idx_story_point_model_routing_tenant ON story_point_model_routing(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_system_policies_key ON system_policies(policy_key);
CREATE INDEX IF NOT EXISTS idx_task_attachments_task ON task_attachments(task_id);
CREATE INDEX IF NOT EXISTS idx_task_creation_events_tenant ON task_creation_events(tenant_id);
CREATE INDEX IF NOT EXISTS idx_task_deps_blocked ON task_dependencies(blocked_id);
CREATE INDEX IF NOT EXISTS idx_task_deps_blocker ON task_dependencies(blocker_id);
CREATE INDEX IF NOT EXISTS idx_task_events_agent ON task_events(agent_id);
CREATE INDEX IF NOT EXISTS idx_task_events_created ON task_events(created_at);
CREATE INDEX IF NOT EXISTS idx_task_events_move_type ON task_events(move_type);
CREATE INDEX IF NOT EXISTS idx_task_events_project ON task_events(project_id);
CREATE INDEX IF NOT EXISTS idx_task_events_task ON task_events(task_id);
CREATE INDEX IF NOT EXISTS idx_task_events_to_status ON task_events(to_status);
CREATE INDEX IF NOT EXISTS idx_task_field_schemas_lookup ON task_field_schemas(tenant_id, sprint_type_key, task_type);
CREATE INDEX IF NOT EXISTS idx_task_history_task ON task_history(task_id);
CREATE INDEX IF NOT EXISTS idx_task_history_tenant ON task_history(tenant_id);
CREATE INDEX IF NOT EXISTS idx_task_notes_task ON task_notes(task_id);
CREATE INDEX IF NOT EXISTS idx_task_notes_tenant ON task_notes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_task_outcome_metrics_tenant ON task_outcome_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_task_relationships_source ON task_relationships(source_task_id);
CREATE INDEX IF NOT EXISTS idx_task_relationships_target ON task_relationships(target_task_id);
CREATE INDEX IF NOT EXISTS idx_task_relationships_type ON task_relationships(relationship_type_key);
CREATE INDEX IF NOT EXISTS idx_tasks_agent ON tasks(agent_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_agent ON tasks(assigned_agent_id);
CREATE INDEX IF NOT EXISTS idx_tasks_defect_type ON tasks(defect_type);
CREATE INDEX IF NOT EXISTS idx_tasks_generated_lookup ON tasks(recurring_series_id, scheduled_for) WHERE recurring_series_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_generated_occurrence_unique ON tasks(recurring_series_id, scheduled_for) WHERE recurring_series_id IS NOT NULL AND scheduled_for IS NOT NULL AND generated_from = 'recurring_task_series';
CREATE INDEX IF NOT EXISTS idx_tasks_origin ON tasks(origin_task_id);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_schedule_run ON tasks(schedule_run_id) WHERE schedule_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_tenant ON tasks(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tce_created ON task_creation_events(created_at);
CREATE INDEX IF NOT EXISTS idx_tce_job ON task_creation_events(job_id);
CREATE INDEX IF NOT EXISTS idx_tce_project ON task_creation_events(project_id);
CREATE INDEX IF NOT EXISTS idx_tce_source ON task_creation_events(source);
CREATE INDEX IF NOT EXISTS idx_tce_sprint ON task_creation_events(sprint_id);
CREATE INDEX IF NOT EXISTS idx_tce_task ON task_creation_events(task_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenants_single_default ON tenants(is_default) WHERE is_default = 1;
CREATE INDEX IF NOT EXISTS idx_tom_job ON task_outcome_metrics(job_id);
CREATE INDEX IF NOT EXISTS idx_tom_project ON task_outcome_metrics(project_id);
CREATE INDEX IF NOT EXISTS idx_tom_quality ON task_outcome_metrics(outcome_quality);
CREATE INDEX IF NOT EXISTS idx_tom_recorded ON task_outcome_metrics(recorded_at);
CREATE INDEX IF NOT EXISTS idx_tom_sprint ON task_outcome_metrics(sprint_id);
CREATE INDEX IF NOT EXISTS idx_tom_task ON task_outcome_metrics(task_id);
CREATE INDEX IF NOT EXISTS idx_tools_enabled ON tools(enabled);
CREATE INDEX IF NOT EXISTS idx_tools_slug ON tools(slug);
CREATE INDEX IF NOT EXISTS idx_tools_tenant ON tools(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tools_tenant_slug ON tools(tenant_id, slug);
CREATE INDEX IF NOT EXISTS idx_transition_req_lookup ON transition_requirements(task_type, outcome);
CREATE INDEX IF NOT EXISTS idx_transition_req_type ON transition_requirements(task_type);
CREATE INDEX IF NOT EXISTS idx_workflow_file_versions_file ON workflow_file_versions(file_id, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_file_versions_scope ON workflow_file_versions(tenant_id, project_id, workflow_id, file_id);
CREATE INDEX IF NOT EXISTS idx_workflow_files_workflow ON workflow_files(tenant_id, project_id, workflow_id);

-- === BASELINE SECTION: foreign-keys ===
ALTER TABLE agent_mcp_assignments ADD CONSTRAINT fk_agent_mcp_assignments_0 FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers (id) ON DELETE CASCADE;
ALTER TABLE agent_mcp_assignments ADD CONSTRAINT fk_agent_mcp_assignments_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE agent_mcp_capability_policies ADD CONSTRAINT fk_agent_mcp_capability_policies_0 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE agent_tool_assignments ADD CONSTRAINT fk_agent_tool_assignments_0 FOREIGN KEY (tool_id) REFERENCES tools (id) ON DELETE CASCADE;
ALTER TABLE agent_tool_assignments ADD CONSTRAINT fk_agent_tool_assignments_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE agents ADD CONSTRAINT fk_agents_0 FOREIGN KEY (provider_connection_id) REFERENCES provider_connections (id) ON DELETE SET NULL;
ALTER TABLE agents ADD CONSTRAINT fk_agents_1 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE agents ADD CONSTRAINT fk_agents_2 FOREIGN KEY (github_identity_id) REFERENCES github_identities (id) ON DELETE SET NULL;
ALTER TABLE agents ADD CONSTRAINT fk_agents_3 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE SET NULL;
ALTER TABLE agents ADD CONSTRAINT fk_agents_4 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
ALTER TABLE canonical_chat_sessions ADD CONSTRAINT fk_canonical_chat_sessions_0 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE chat_attachments ADD CONSTRAINT fk_chat_attachments_0 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE chat_attachments ADD CONSTRAINT fk_chat_attachments_1 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE CASCADE;
ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_1 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_2 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE dev_db_sync_audit ADD CONSTRAINT fk_dev_db_sync_audit_0 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE dispatch_log ADD CONSTRAINT fk_dispatch_log_0 FOREIGN KEY (agent_id) REFERENCES agents (id);
ALTER TABLE external_event_mappings ADD CONSTRAINT fk_external_event_mappings_0 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE external_event_mappings ADD CONSTRAINT fk_external_event_mappings_1 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE external_event_mappings ADD CONSTRAINT fk_external_event_mappings_2 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE external_task_event_receipts ADD CONSTRAINT fk_external_task_event_receipts_0 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE github_identities ADD CONSTRAINT fk_github_identities_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE instance_artifacts ADD CONSTRAINT fk_instance_artifacts_0 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE instance_artifacts ADD CONSTRAINT fk_instance_artifacts_1 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE CASCADE;
ALTER TABLE integrity_events ADD CONSTRAINT fk_integrity_events_0 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE integrity_events ADD CONSTRAINT fk_integrity_events_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE integrity_events ADD CONSTRAINT fk_integrity_events_2 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
ALTER TABLE integrity_events ADD CONSTRAINT fk_integrity_events_3 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE job_instances ADD CONSTRAINT fk_job_instances_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE job_instances ADD CONSTRAINT fk_job_instances_1 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE job_instances ADD CONSTRAINT fk_job_instances_2 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE logs ADD CONSTRAINT fk_logs_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE logs ADD CONSTRAINT fk_logs_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE logs ADD CONSTRAINT fk_logs_2 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE mcp_api_keys ADD CONSTRAINT fk_mcp_api_keys_0 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;
ALTER TABLE mcp_servers ADD CONSTRAINT fk_mcp_servers_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE notification_records ADD CONSTRAINT fk_notification_records_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE openclaw_transcript_ingest_state ADD CONSTRAINT fk_openclaw_transcript_ingest_state_0 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE CASCADE;
ALTER TABLE project_audit_log ADD CONSTRAINT fk_project_audit_log_0 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE project_file_versions ADD CONSTRAINT fk_project_file_versions_0 FOREIGN KEY (file_id) REFERENCES project_files (id) ON DELETE CASCADE;
ALTER TABLE project_file_versions ADD CONSTRAINT fk_project_file_versions_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE project_files ADD CONSTRAINT fk_project_files_0 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE projects ADD CONSTRAINT fk_projects_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE provider_config ADD CONSTRAINT fk_provider_config_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE provider_connections ADD CONSTRAINT fk_provider_connections_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE recurring_task_runs ADD CONSTRAINT fk_recurring_task_runs_0 FOREIGN KEY (created_task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE recurring_task_runs ADD CONSTRAINT fk_recurring_task_runs_1 FOREIGN KEY (series_id) REFERENCES recurring_task_series (id) ON DELETE CASCADE;
ALTER TABLE recurring_task_series ADD CONSTRAINT fk_recurring_task_series_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE recurring_task_series ADD CONSTRAINT fk_recurring_task_series_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE recurring_task_series ADD CONSTRAINT fk_recurring_task_series_2 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE recurring_task_series ADD CONSTRAINT fk_recurring_task_series_3 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE routing_config ADD CONSTRAINT fk_routing_config_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE routing_config ADD CONSTRAINT fk_routing_config_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE routing_transitions ADD CONSTRAINT fk_routing_transitions_0 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE security_events ADD CONSTRAINT fk_security_events_0 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE security_events ADD CONSTRAINT fk_security_events_1 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE security_events ADD CONSTRAINT fk_security_events_2 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE session_messages ADD CONSTRAINT fk_session_messages_0 FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE;
ALTER TABLE sessions ADD CONSTRAINT fk_sessions_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sessions ADD CONSTRAINT fk_sessions_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
ALTER TABLE sessions ADD CONSTRAINT fk_sessions_2 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE sessions ADD CONSTRAINT fk_sessions_3 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE sessions ADD CONSTRAINT fk_sessions_4 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE skills ADD CONSTRAINT fk_skills_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_routing_rules ADD CONSTRAINT fk_sprint_task_routing_rules_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_routing_rules ADD CONSTRAINT fk_sprint_task_routing_rules_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE sprint_task_routing_rules ADD CONSTRAINT fk_sprint_task_routing_rules_2 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_routing_rules ADD CONSTRAINT fk_sprint_task_routing_rules_3 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_statuses ADD CONSTRAINT fk_sprint_task_statuses_0 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transition_requirement_tombstones ADD CONSTRAINT fk_sprint_task_transition_requirement_tombstones_0 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transition_requirements ADD CONSTRAINT fk_sprint_task_transition_requirements_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transition_requirements ADD CONSTRAINT fk_sprint_task_transition_requirements_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transition_requirements ADD CONSTRAINT fk_sprint_task_transition_requirements_2 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transitions ADD CONSTRAINT fk_sprint_task_transitions_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transitions ADD CONSTRAINT fk_sprint_task_transitions_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE sprint_task_transitions ADD CONSTRAINT fk_sprint_task_transitions_2 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE sprint_type_outcomes ADD CONSTRAINT fk_sprint_type_outcomes_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_type_relationship_types ADD CONSTRAINT fk_sprint_type_relationship_types_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_type_task_statuses ADD CONSTRAINT fk_sprint_type_task_statuses_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_type_task_types ADD CONSTRAINT fk_sprint_type_task_types_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_types ADD CONSTRAINT fk_sprint_types_0 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE sprint_types ADD CONSTRAINT fk_sprint_types_1 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_workflow_statuses ADD CONSTRAINT fk_sprint_workflow_statuses_0 FOREIGN KEY (template_id) REFERENCES sprint_workflow_templates (id) ON DELETE CASCADE;
ALTER TABLE sprint_workflow_templates ADD CONSTRAINT fk_sprint_workflow_templates_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprint_workflow_transitions ADD CONSTRAINT fk_sprint_workflow_transitions_0 FOREIGN KEY (template_id) REFERENCES sprint_workflow_templates (id) ON DELETE CASCADE;
ALTER TABLE sprints ADD CONSTRAINT fk_sprints_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE sprints ADD CONSTRAINT fk_sprints_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE story_point_model_routing ADD CONSTRAINT fk_story_point_model_routing_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE story_point_model_routing ADD CONSTRAINT fk_story_point_model_routing_1 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE story_point_model_routing ADD CONSTRAINT fk_story_point_model_routing_2 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE task_attachments ADD CONSTRAINT fk_task_attachments_0 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_creation_events ADD CONSTRAINT fk_task_creation_events_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE task_creation_events ADD CONSTRAINT fk_task_creation_events_1 FOREIGN KEY (agent_id) REFERENCES agents (id);
ALTER TABLE task_creation_events ADD CONSTRAINT fk_task_creation_events_2 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE SET NULL;
ALTER TABLE task_creation_events ADD CONSTRAINT fk_task_creation_events_3 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
ALTER TABLE task_creation_events ADD CONSTRAINT fk_task_creation_events_4 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_dependencies ADD CONSTRAINT fk_task_dependencies_0 FOREIGN KEY (blocked_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_dependencies ADD CONSTRAINT fk_task_dependencies_1 FOREIGN KEY (blocker_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_events ADD CONSTRAINT fk_task_events_0 FOREIGN KEY (instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE task_events ADD CONSTRAINT fk_task_events_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE task_events ADD CONSTRAINT fk_task_events_2 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
ALTER TABLE task_events ADD CONSTRAINT fk_task_events_3 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_field_schemas ADD CONSTRAINT fk_task_field_schemas_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE task_history ADD CONSTRAINT fk_task_history_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE task_history ADD CONSTRAINT fk_task_history_1 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_notes ADD CONSTRAINT fk_task_notes_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE task_notes ADD CONSTRAINT fk_task_notes_1 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_outcome_metrics ADD CONSTRAINT fk_task_outcome_metrics_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE task_outcome_metrics ADD CONSTRAINT fk_task_outcome_metrics_1 FOREIGN KEY (agent_id) REFERENCES agents (id);
ALTER TABLE task_outcome_metrics ADD CONSTRAINT fk_task_outcome_metrics_2 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE SET NULL;
ALTER TABLE task_outcome_metrics ADD CONSTRAINT fk_task_outcome_metrics_3 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
ALTER TABLE task_outcome_metrics ADD CONSTRAINT fk_task_outcome_metrics_4 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_relationships ADD CONSTRAINT fk_task_relationships_0 FOREIGN KEY (target_task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_relationships ADD CONSTRAINT fk_task_relationships_1 FOREIGN KEY (source_task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_1 FOREIGN KEY (assigned_agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_2 FOREIGN KEY (schedule_run_id) REFERENCES recurring_task_runs (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_3 FOREIGN KEY (recurring_series_id) REFERENCES recurring_task_series (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_4 FOREIGN KEY (review_owner_agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_5 FOREIGN KEY (origin_task_id) REFERENCES tasks (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_6 FOREIGN KEY (sprint_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_7 FOREIGN KEY (active_instance_id) REFERENCES job_instances (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_8 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_9 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE workflow_file_versions ADD CONSTRAINT fk_workflow_file_versions_0 FOREIGN KEY (file_id) REFERENCES workflow_files (id) ON DELETE CASCADE;
ALTER TABLE workflow_file_versions ADD CONSTRAINT fk_workflow_file_versions_1 FOREIGN KEY (workflow_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE workflow_file_versions ADD CONSTRAINT fk_workflow_file_versions_2 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE workflow_files ADD CONSTRAINT fk_workflow_files_0 FOREIGN KEY (workflow_id) REFERENCES sprints (id) ON DELETE CASCADE;
ALTER TABLE workflow_files ADD CONSTRAINT fk_workflow_files_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
