-- Audit trail for routing configuration changes.
--
-- A new table rather than more rows in project_audit_log, because that table cannot
-- represent these events: entity_type is constrained to ('project','sprint','job_template'),
-- project_id is NOT NULL behind an ON DELETE CASCADE foreign key, and there is no tenant_id
-- at all. Routing configuration is tenant-scoped and is legitimately project-less — a global
-- transition has no project — so reusing it would mean relaxing constraints that every
-- existing writer of that table depends on.
--
-- project_id is ON DELETE SET NULL, deliberately unlike project_audit_log's CASCADE. The
-- trail exists to answer "who changed this, and from what", and a project being deleted is
-- one of the moments that question actually gets asked; cascading would erase the evidence
-- precisely when it is wanted.
--
-- before_json/after_json are the full row snapshots and are the intended input to an undo;
-- `changes` is the field-level diff in the { field: { old, new } } shape the existing audit
-- renderer already understands.
--
-- Idempotent across both namings of the workflow table, so it is safe to apply before or
-- after the pending rename in migration 10.

BEGIN;

CREATE TABLE routing_config_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint,
  workflow_type text NOT NULL,
  workflow_id bigint,
  entity_table text NOT NULL,
  entity_id bigint,
  entity_key text NOT NULL DEFAULT '',
  action text NOT NULL,
  actor text NOT NULL DEFAULT 'unknown',
  actor_kind text NOT NULL DEFAULT 'unknown',
  before_json text NOT NULL DEFAULT 'null',
  after_json text NOT NULL DEFAULT 'null',
  changes text NOT NULL DEFAULT '{}',
  batch_id text NOT NULL DEFAULT '',
  affected_workflow_count integer,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

ALTER TABLE routing_config_audit_log
  ADD CONSTRAINT fk_routing_config_audit_log_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE routing_config_audit_log
  ADD CONSTRAINT fk_routing_config_audit_log_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;

-- The workflow table is "workflows" once migration 10 has been applied and "sprints" before
-- it. Both orderings are reachable — 10 is still pending on production — so the target is
-- resolved at apply time rather than named.
DO $$
BEGIN
  IF to_regclass('public.workflows') IS NOT NULL THEN
    ALTER TABLE routing_config_audit_log
      ADD CONSTRAINT fk_routing_config_audit_log_2 FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE SET NULL;
  ELSE
    ALTER TABLE routing_config_audit_log
      ADD CONSTRAINT fk_routing_config_audit_log_2 FOREIGN KEY (workflow_id) REFERENCES sprints (id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_routing_config_audit_log_tenant ON routing_config_audit_log(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_routing_config_audit_log_project ON routing_config_audit_log(project_id);
CREATE INDEX IF NOT EXISTS idx_routing_config_audit_log_entity ON routing_config_audit_log(entity_table, entity_id);
CREATE INDEX IF NOT EXISTS idx_routing_config_audit_log_batch ON routing_config_audit_log(batch_id);
CREATE INDEX IF NOT EXISTS idx_routing_config_audit_log_created ON routing_config_audit_log(created_at);

COMMIT;
