-- Durable runtime-driver state, separate from workflow/task outcomes.
--
-- runtime_executions is the current execution record for one job instance. The
-- boundary and launch/handle JSON are versioned application contracts; launch
-- specs are explicitly sanitized and must contain env names, never values.
-- runtime_checkpoints is append-only and ordered per execution so recovery can
-- prove which session/transcript cursor it is resuming.

BEGIN;

DO $migration$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'job_instances'::regclass
      AND conname = 'uq_job_instances_tenant_id_id'
  ) THEN
    ALTER TABLE job_instances
      ADD CONSTRAINT uq_job_instances_tenant_id_id UNIQUE (tenant_id, id);
  END IF;
END
$migration$;

CREATE TABLE runtime_executions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  instance_id bigint NOT NULL,
  boundary_version integer NOT NULL DEFAULT 1 CHECK (boundary_version > 0),
  boundary_json jsonb NOT NULL,
  boundary_fingerprint text NOT NULL,
  runtime_type text NOT NULL,
  driver text NOT NULL,
  backend text NOT NULL,
  execution_target_id text NOT NULL,
  sanitized_launch_spec jsonb,
  opaque_handle jsonb,
  state text NOT NULL DEFAULT 'preparing' CHECK (state IN (
    'preparing', 'starting', 'running', 'interrupting',
    'succeeded', 'failed', 'cancelled', 'lost'
  )),
  session_id text,
  capability_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  lease_owner text,
  lease_expires_at text,
  heartbeat_at text,
  terminal_reason text,
  terminal_error text,
  terminal_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at text,
  ended_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT uq_runtime_executions_tenant_id_id UNIQUE (tenant_id, id),
  CONSTRAINT uq_runtime_executions_instance UNIQUE (tenant_id, instance_id),
  CONSTRAINT fk_runtime_executions_instance FOREIGN KEY (tenant_id, instance_id)
    REFERENCES job_instances (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT ck_runtime_executions_boundary_object CHECK (jsonb_typeof(boundary_json) = 'object'),
  CONSTRAINT ck_runtime_executions_launch_object CHECK (
    sanitized_launch_spec IS NULL OR jsonb_typeof(sanitized_launch_spec) = 'object'
  ),
  CONSTRAINT ck_runtime_executions_handle_object CHECK (
    opaque_handle IS NULL OR jsonb_typeof(opaque_handle) = 'object'
  ),
  CONSTRAINT ck_runtime_executions_capabilities_array CHECK (
    jsonb_typeof(capability_snapshot) = 'array'
  ),
  CONSTRAINT ck_runtime_executions_terminal_metadata_object CHECK (
    jsonb_typeof(terminal_metadata) = 'object'
  )
);

CREATE INDEX idx_runtime_executions_state_heartbeat
  ON runtime_executions (tenant_id, state, heartbeat_at);
CREATE INDEX idx_runtime_executions_lease
  ON runtime_executions (lease_expires_at)
  WHERE lease_expires_at IS NOT NULL;
CREATE INDEX idx_runtime_executions_runtime
  ON runtime_executions (tenant_id, runtime_type, state);

CREATE TABLE runtime_checkpoints (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  execution_id bigint NOT NULL,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  sequence integer NOT NULL CHECK (sequence >= 0),
  kind text NOT NULL CHECK (kind IN (
    'prepared', 'launched', 'session', 'progress',
    'interrupt_requested', 'interrupted', 'terminal', 'reconciled'
  )),
  state text NOT NULL CHECK (state IN (
    'preparing', 'starting', 'running', 'interrupting',
    'succeeded', 'failed', 'cancelled', 'lost'
  )),
  session_id text,
  boundary_fingerprint text NOT NULL,
  transcript_cursor jsonb,
  checkpoint_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT uq_runtime_checkpoints_execution_sequence UNIQUE (execution_id, sequence),
  CONSTRAINT fk_runtime_checkpoints_execution FOREIGN KEY (tenant_id, execution_id)
    REFERENCES runtime_executions (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT ck_runtime_checkpoints_cursor_object CHECK (
    transcript_cursor IS NULL OR jsonb_typeof(transcript_cursor) = 'object'
  ),
  CONSTRAINT ck_runtime_checkpoints_data_object CHECK (
    jsonb_typeof(checkpoint_data) = 'object'
  )
);

CREATE INDEX idx_runtime_checkpoints_execution_created
  ON runtime_checkpoints (execution_id, sequence DESC);
CREATE INDEX idx_runtime_checkpoints_tenant_kind
  ON runtime_checkpoints (tenant_id, kind, created_at);

COMMIT;
