-- Agent teams: named groups of agents with a shared goal, mutual awareness, a default
-- capability bundle, and a reusable routing shape that can be stamped onto a workflow.
--
-- See docs/agent-teams-plan.md for the design and the decisions behind it.
--
-- VOCABULARY. New tables are born with workflow terminology, following the precedent set by
-- 14-routing-config-audit-log.sql. The physical rename in staged/10 is still unapplied, so the
-- workflow table is "sprints" here and "workflows" after it lands; every reference below
-- resolves the target at apply time rather than naming it, exactly as 14 does.
--
-- Deliberately NOT a join table for team-to-workflow ownership. One team owns a workflow, so
-- that is a column on the workflow table. A join table would need a sprint_id column, which the
-- regenerated rename mapping would then rewrite, leaving a brand-new table straddling both
-- vocabularies for no benefit.

BEGIN;

-- === teams ===================================================================

CREATE TABLE teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  -- description is operator-facing; goal and charter are injected into every member's prompt.
  description text NOT NULL DEFAULT '',
  goal text NOT NULL DEFAULT '',
  charter text NOT NULL DEFAULT '',
  project_id bigint,
  skill_names text NOT NULL DEFAULT '[]',
  -- Bumped on any change that alters the rendered context block, so a transcript can be tied
  -- back to the exact team definition it ran under.
  context_version bigint NOT NULL DEFAULT 1,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  deleted_at text,
  PRIMARY KEY (id)
);

ALTER TABLE teams
  ADD CONSTRAINT fk_teams_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE teams
  ADD CONSTRAINT fk_teams_1 FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;

-- Soft-deleted teams keep their rows (workflows may still reference them through provenance),
-- so slug uniqueness has to exclude them or a name can never be reused.
CREATE UNIQUE INDEX idx_teams_tenant_slug ON teams(tenant_id, slug) WHERE deleted_at IS NULL;
CREATE INDEX idx_teams_tenant ON teams(tenant_id);
CREATE INDEX idx_teams_project ON teams(project_id);

-- Referenced by team_members and team_routing_rules to keep membership and rule rows inside the
-- owning tenant, the same guard agent_tool_assignments relies on for tools.
ALTER TABLE teams
  ADD CONSTRAINT uq_teams_tenant_id_id UNIQUE (tenant_id, id);

-- === membership ==============================================================

-- An agent may belong to several teams. Which team speaks for a given dispatch is resolved at
-- dispatch time from workflow ownership, falling back to sole membership and then is_primary;
-- see resolveTeamContext() in api/src/domains/teams/context.ts.
CREATE TABLE team_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  team_id bigint NOT NULL,
  agent_id bigint NOT NULL,
  -- member_role and responsibilities are injected verbatim into teammates' prompts.
  member_role text NOT NULL DEFAULT '',
  responsibilities text NOT NULL DEFAULT '',
  is_lead bigint NOT NULL DEFAULT 0,
  is_primary bigint NOT NULL DEFAULT 0,
  sort_order bigint NOT NULL DEFAULT 0,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

ALTER TABLE team_members
  ADD CONSTRAINT fk_team_members_0 FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE;
ALTER TABLE team_members
  ADD CONSTRAINT fk_team_members_1 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX idx_team_members_team_agent ON team_members(team_id, agent_id);
CREATE INDEX idx_team_members_agent ON team_members(agent_id);
-- Members render in (sort_order, id) order so the injected block is byte-stable across
-- dispatches; churn here would defeat prompt caching on every run.
CREATE INDEX idx_team_members_team_order ON team_members(team_id, sort_order, id);
-- At most one primary membership per agent, so the multi-team tiebreak is total.
CREATE UNIQUE INDEX idx_team_members_agent_primary ON team_members(agent_id) WHERE is_primary = 1;

-- === capability defaults =====================================================

-- Shape-identical to agent_tool_assignments / agent_mcp_assignments on purpose: the effective
-- set is the union of team and agent grants, and an agent row with enabled = 0 is an explicit
-- opt-out from a team grant. Keeping the shapes identical is what makes that merge trivial.
CREATE TABLE team_tool_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  team_id bigint NOT NULL,
  tool_id bigint NOT NULL,
  overrides text NOT NULL DEFAULT '{}',
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

ALTER TABLE team_tool_assignments
  ADD CONSTRAINT fk_team_tool_assignments_0 FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE;
ALTER TABLE team_tool_assignments
  ADD CONSTRAINT fk_team_tool_assignments_1 FOREIGN KEY (tool_id) REFERENCES tools (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX idx_team_tool_assignments_team_tool ON team_tool_assignments(team_id, tool_id);
CREATE INDEX idx_team_tool_assignments_tool ON team_tool_assignments(tool_id);

CREATE TABLE team_mcp_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  team_id bigint NOT NULL,
  mcp_server_id bigint NOT NULL,
  overrides text NOT NULL DEFAULT '{}',
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

ALTER TABLE team_mcp_assignments
  ADD CONSTRAINT fk_team_mcp_assignments_0 FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE;
ALTER TABLE team_mcp_assignments
  ADD CONSTRAINT fk_team_mcp_assignments_1 FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX idx_team_mcp_assignments_team_server ON team_mcp_assignments(team_id, mcp_server_id);
CREATE INDEX idx_team_mcp_assignments_server ON team_mcp_assignments(mcp_server_id);

-- === routing templates =======================================================

-- Templates, not live routing. These expand into real workflow routing rules when applied to a
-- workflow; the resolver, trace, preview, graph and audit paths stay untouched.
--
-- A rule targets either a concrete agent or a member_role. Role targeting is what makes a
-- template portable: "in_review -> Reviewer" survives swapping which agent holds Reviewer.
CREATE TABLE team_routing_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  team_id bigint NOT NULL,
  workflow_type text,
  task_type text,
  status text NOT NULL,
  agent_id bigint,
  member_role text NOT NULL DEFAULT '',
  priority bigint NOT NULL DEFAULT 0,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT ck_team_routing_rules_target CHECK (agent_id IS NOT NULL OR member_role <> '')
);

ALTER TABLE team_routing_rules
  ADD CONSTRAINT fk_team_routing_rules_0 FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE;
ALTER TABLE team_routing_rules
  ADD CONSTRAINT fk_team_routing_rules_1 FOREIGN KEY (team_id, tenant_id) REFERENCES teams (id, tenant_id) ON DELETE CASCADE;
ALTER TABLE team_routing_rules
  ADD CONSTRAINT fk_team_routing_rules_2 FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE SET NULL;

CREATE INDEX idx_team_routing_rules_team ON team_routing_rules(team_id, workflow_type, status);
CREATE INDEX idx_team_routing_rules_agent ON team_routing_rules(agent_id);

-- === workflow ownership and rule provenance ==================================

-- Both target tables carry either vocabulary depending on whether staged/10 has landed, so the
-- name is resolved at apply time. ON DELETE SET NULL throughout: deleting a team must never
-- delete the routing rules a workflow is actively running on, nor the workflow itself. Those
-- rules become locally-owned, which is the correct failure mode.
DO $migration$
DECLARE
  workflow_table text;
  routing_table text;
BEGIN
  workflow_table := CASE WHEN to_regclass('public.workflows') IS NOT NULL THEN 'workflows' ELSE 'sprints' END;
  routing_table := CASE
    WHEN to_regclass('public.workflow_task_routing_rules') IS NOT NULL THEN 'workflow_task_routing_rules'
    ELSE 'sprint_task_routing_rules'
  END;

  EXECUTE format('ALTER TABLE %I ADD COLUMN team_id bigint', workflow_table);
  EXECUTE format(
    'ALTER TABLE %I ADD CONSTRAINT fk_%s_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE SET NULL',
    workflow_table, workflow_table
  );
  EXECUTE format('CREATE INDEX idx_%s_team ON %I(team_id)', workflow_table, workflow_table);

  EXECUTE format('ALTER TABLE %I ADD COLUMN source_team_id bigint', routing_table);
  EXECUTE format('ALTER TABLE %I ADD COLUMN source_team_rule_id bigint', routing_table);
  -- Snapshot of the values written at the last apply. Without it, "the operator edited this
  -- rule" and "the template changed" are the same observation — the current row simply differs
  -- from the template — and the two need opposite handling: leave alone versus resync.
  EXECUTE format(
    'ALTER TABLE %I ADD COLUMN source_team_applied_json text NOT NULL DEFAULT ''null''',
    routing_table
  );
  EXECUTE format(
    'ALTER TABLE %I ADD CONSTRAINT fk_%s_source_team FOREIGN KEY (source_team_id) REFERENCES teams (id) ON DELETE SET NULL',
    routing_table, routing_table
  );
  EXECUTE format(
    'ALTER TABLE %I ADD CONSTRAINT fk_%s_source_team_rule FOREIGN KEY (source_team_rule_id) REFERENCES team_routing_rules (id) ON DELETE SET NULL',
    routing_table, routing_table
  );
  EXECUTE format('CREATE INDEX idx_%s_source_team ON %I(source_team_id)', routing_table, routing_table);
END
$migration$;

COMMIT;
