-- Migration 22: what Agent HQ actually handed each agent, and where each piece came from.
--
-- Until now the assembled prompt was not persisted anywhere. runtime_executions.boundary_json
-- records prompt.bundleFingerprint — a hash — and the text itself survived only if the runtime's
-- transcript happened to be ingested back into chat_messages, which is runtime-dependent and
-- carries no section structure. "What did run #412 actually receive, and which team definition
-- and contract template produced it" was therefore unanswerable after the fact.
--
-- ONE ROW PER INSTANCE. A job instance is dispatched once, so the bundle is immutable and keyed
-- (tenant_id, instance_id) exactly like runtime_executions. A retry is a new instance and gets
-- its own row, which is what makes run-to-run diffing possible.
--
-- PROMPT TEXT ONCE. segments_json holds [start, end) offsets into prompt_text rather than copies
-- of it, so a 40KB prompt costs 40KB plus a small index, and a rendered segment cannot drift
-- from the bytes the agent received.
--
-- NOT ON job_instances.payload_sent. That column is small dispatch metadata read by instance list
-- queries; prompts are 10-50KB and would be dragged into every one of them.
--
-- VOCABULARY. Born with workflow terminology per the precedent in 14-routing-config-audit-log.sql
-- and 21-agent-teams.sql. The task/instance columns below are named for tables that exist today.

BEGIN;

CREATE TABLE dispatch_context_bundles (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  instance_id bigint NOT NULL,
  -- Survives a database restore, so an exported bundle can be re-associated with its run.
  durable_run_id text,
  -- Null for dispatches that are not task work (workflow summaries, ad-hoc runs).
  task_id bigint,
  agent_id bigint,
  bundle_version integer NOT NULL DEFAULT 1 CHECK (bundle_version > 0),
  -- The exact text handed to the runtime, stored raw. Redaction happens on read: redacting on
  -- write would break equality with prompt_fingerprint and with the runtime boundary's
  -- prompt.bundleFingerprint, which is the only way to prove a stored bundle belongs to its run.
  prompt_text text NOT NULL,
  -- Ordered [{kind,label,start,end,chars,injected,source,omission}], including segments that were
  -- considered and not injected. Absent context is harder to debug than present context.
  segments_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  prompt_chars bigint NOT NULL DEFAULT 0,
  -- runtimeBoundaryDigest('runtime-prompt-bundle-v1', prompt_text).
  prompt_fingerprint text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT uq_dispatch_context_bundles_instance UNIQUE (tenant_id, instance_id),
  CONSTRAINT fk_dispatch_context_bundles_instance FOREIGN KEY (tenant_id, instance_id)
    REFERENCES job_instances (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT ck_dispatch_context_bundles_segments_array CHECK (
    jsonb_typeof(segments_json) = 'array'
  )
);

-- The viewer's primary query: every captured run for one task, newest first.
CREATE INDEX idx_dispatch_context_bundles_task
  ON dispatch_context_bundles (tenant_id, task_id, id DESC);

-- Retention sweeps and "what did this agent get lately" both scan by age.
CREATE INDEX idx_dispatch_context_bundles_created
  ON dispatch_context_bundles (tenant_id, created_at);

COMMIT;
