-- Migration 23: OAuth 2.1 authorization for the remote MCP transport.
--
-- Remote MCP clients (Claude connectors, ChatGPT custom connectors) offer exactly two auth
-- modes: OAuth, or none. Neither has a field for a static bearer token, so the /mcp endpoint
-- added in the Streamable HTTP work is unreachable from them without an authorization server.
-- These tables are that server's storage.
--
-- THE ACCESS TOKEN IS AN MCP API KEY. There is deliberately no oauth_access_tokens table. An
-- issued access token is a row in mcp_api_keys with an expiry and a grant back-reference, so
-- resolveMcpApiIdentityForKey, the capability policy, the audit actor, and the /mcp router all
-- keep working unchanged — OAuth becomes token issuance and lifecycle over the identity model
-- that already exists, rather than a second, parallel one. The alternative (self-signed JWTs)
-- would have needed a separate long-lived key for the server to call its own API with, which is
-- the static secret OAuth exists to remove.
--
-- EVERYTHING IS STORED HASHED. Authorization codes and refresh tokens are held as sha256 hashes
-- exactly as mcp_api_keys.key_hash already is, so a database read never yields a usable
-- credential. Client secrets do not appear at all — the server registers public clients and
-- relies on PKCE, which OAuth 2.1 requires of every client regardless.

BEGIN;

-- Registered OAuth clients. Populated by dynamic client registration (RFC 7591) when a connector
-- registers itself, and by hand for clients configured with a pre-issued id.
CREATE TABLE mcp_oauth_clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  client_id text NOT NULL,
  -- Always NULL today: the server registers public clients and relies on PKCE. Reserved so
  -- adding confidential clients later does not need a second migration.
  client_secret_hash text,
  client_name text NOT NULL DEFAULT '',
  -- JSON array. Matched exactly at /authorize; no prefix or wildcard matching anywhere.
  redirect_uris text NOT NULL DEFAULT '[]',
  grant_types text NOT NULL DEFAULT '["authorization_code","refresh_token"]',
  response_types text NOT NULL DEFAULT '["code"]',
  token_endpoint_auth_method text NOT NULL DEFAULT 'none',
  scope text,
  client_uri text,
  registered_via text NOT NULL DEFAULT 'dcr',
  client_id_issued_at bigint NOT NULL,
  client_secret_expires_at bigint,
  disabled_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT uq_mcp_oauth_clients_client_id UNIQUE (client_id)
);

-- One row per authorization request. Written when the operator approves at the consent screen
-- and consumed exactly once at the token endpoint.
--
-- The row carries the PKCE challenge, the redirect URI, and the resource indicator from the
-- original request so the token endpoint validates against what was actually authorized rather
-- than against whatever the token request claims.
CREATE TABLE mcp_oauth_authorization_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  code_hash text NOT NULL,
  client_id text NOT NULL,
  agent_id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  redirect_uri text NOT NULL,
  code_challenge text NOT NULL,
  resource text,
  scopes text NOT NULL DEFAULT '[]',
  expires_at text NOT NULL,
  -- Set on first exchange. A second exchange finds it non-null and is refused.
  consumed_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT uq_mcp_oauth_authorization_codes_hash UNIQUE (code_hash),
  CONSTRAINT fk_mcp_oauth_codes_agent FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE
);

-- A grant is one client's standing authorization for one agent identity: the thing a person
-- revokes when they disconnect a connector. Access tokens hang off it in mcp_api_keys and
-- refresh tokens rotate within it.
CREATE TABLE mcp_oauth_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  client_id text NOT NULL,
  agent_id bigint NOT NULL,
  tenant_id bigint NOT NULL,
  scopes text NOT NULL DEFAULT '[]',
  resource text,
  -- Kept even after the token is superseded or revoked. Clearing it would make a replayed token
  -- unrecognisable, and an unrecognisable replay is one that cannot trigger family revocation —
  -- which is the entire point of rotating. These are sha256 hashes, so retaining them is not
  -- retaining credentials.
  refresh_token_hash text,
  -- Set when this row supersedes another during rotation, so a replayed refresh token can be
  -- traced back to the family it belongs to and take the whole family down with it.
  rotated_from_id bigint,
  -- Set on the old row at rotation time. Presenting a superseded token is the reuse signal.
  superseded_at text,
  revoked_at text,
  revoked_reason text,
  last_used_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CONSTRAINT uq_mcp_oauth_grants_refresh_hash UNIQUE (refresh_token_hash),
  CONSTRAINT fk_mcp_oauth_grants_agent FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE
);

-- Access tokens are mcp_api_keys rows. Two columns make one an OAuth token: when it dies, and
-- which grant it belongs to. Keys issued the old way leave both NULL and never expire, which is
-- the existing behaviour for runtime and materialized keys.
ALTER TABLE mcp_api_keys ADD COLUMN IF NOT EXISTS expires_at text;
ALTER TABLE mcp_api_keys ADD COLUMN IF NOT EXISTS oauth_grant_id bigint;

-- Revoking a grant means finding its tokens.
CREATE INDEX idx_mcp_api_keys_oauth_grant ON mcp_api_keys (oauth_grant_id);
CREATE INDEX idx_mcp_oauth_grants_client ON mcp_oauth_grants (client_id, agent_id);
-- Expiry sweeps scan codes by age.
CREATE INDEX idx_mcp_oauth_codes_expires ON mcp_oauth_authorization_codes (expires_at);

COMMIT;
