-- Configurable telemetry capture. Triggers cover canonical SQL writers, including
-- imports/reconciliation, and commit their bounded observations atomically.
-- No legacy first-pass or quality summaries are treated as historical facts.
BEGIN;

CREATE TABLE telemetry_capture_sources (
  source text PRIMARY KEY,
  capture_started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  producer_version integer NOT NULL DEFAULT 1,
  history_complete boolean NOT NULL DEFAULT false,
  limitations text NOT NULL DEFAULT 'History before capture began is incomplete.'
);

CREATE TABLE telemetry_source_coverage (
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source text NOT NULL REFERENCES telemetry_capture_sources(source),
  backfill_cursor bigint NOT NULL DEFAULT 0,
  backfill_complete boolean NOT NULL DEFAULT false,
  backfill_updated_at timestamptz,
  last_projected_at timestamptz,
  last_error text,
  PRIMARY KEY (tenant_id, source)
);

CREATE TABLE telemetry_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source text NOT NULL,
  source_key text NOT NULL,
  entity_type text NOT NULL,
  entity_id bigint NOT NULL,
  task_id bigint,
  project_id bigint,
  workflow_id bigint,
  agent_id bigint,
  kind text NOT NULL,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  causation_id text,
  provenance text NOT NULL DEFAULT 'observed',
  producer_version integer NOT NULL DEFAULT 1,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  processed_at timestamptz,
  attempts integer NOT NULL DEFAULT 0,
  retry_at timestamptz,
  last_error text,
  UNIQUE (tenant_id, source_key)
);
CREATE INDEX telemetry_outbox_pending ON telemetry_outbox(id) WHERE processed_at IS NULL;
CREATE INDEX telemetry_outbox_task ON telemetry_outbox(tenant_id,task_id);
CREATE INDEX telemetry_outbox_scope ON telemetry_outbox(tenant_id,project_id,recorded_at);

CREATE TABLE telemetry_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source text NOT NULL,
  source_key text NOT NULL,
  entity_type text NOT NULL,
  entity_id bigint NOT NULL,
  task_id bigint,
  project_id bigint,
  workflow_id bigint,
  agent_id bigint,
  kind text NOT NULL,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL,
  sequence bigint NOT NULL,
  causation_id text,
  provenance text NOT NULL,
  producer_version integer NOT NULL,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  UNIQUE (tenant_id, source_key)
);
CREATE INDEX telemetry_observations_task_time ON telemetry_observations(tenant_id,task_id,occurred_at,sequence);
CREATE INDEX telemetry_observations_scope_time ON telemetry_observations(tenant_id,project_id,kind,occurred_at);
CREATE INDEX telemetry_observations_entity ON telemetry_observations(tenant_id,entity_type,entity_id,sequence);

-- Legacy text timestamps are UTC, regardless of the connection's time zone.
CREATE FUNCTION telemetry_timestamp(raw text, fallback timestamptz) RETURNS timestamptz
LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
  IF raw IS NULL OR raw = '' THEN RETURN fallback; END IF;
  IF raw ~ '(Z|[+-][0-9]{2}:?[0-9]{2})$' THEN RETURN raw::timestamptz; END IF;
  RETURN raw::timestamp AT TIME ZONE 'UTC';
EXCEPTION WHEN invalid_datetime_format OR datetime_field_overflow THEN RETURN fallback;
END $$;

CREATE FUNCTION telemetry_json(raw text) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
  RETURN COALESCE(raw::jsonb, '{}'::jsonb);
EXCEPTION WHEN invalid_text_representation THEN RETURN '{}'::jsonb;
END $$;

-- Explicit allowlists avoid copying credentials, prompts, transcripts, opaque
-- runtime handles, outcome summaries or arbitrary configuration metadata.
CREATE FUNCTION telemetry_pick(row_data jsonb, keys text[]) RETURNS jsonb
LANGUAGE sql IMMUTABLE AS $$
  SELECT COALESCE(jsonb_object_agg(key, value), '{}'::jsonb)
  FROM jsonb_each(row_data) WHERE key = ANY(keys)
$$;

CREATE FUNCTION telemetry_dependency_state(row_data jsonb) RETURNS jsonb LANGUAGE sql STABLE AS $$
  SELECT jsonb_build_object(
    'unresolved_dependencies',CASE WHEN COALESCE(bool_and(COALESCE(b.tenant_id=(row_data->>'tenant_id')::bigint,false)),true)
      THEN COUNT(*) FILTER (WHERE COALESCE(ws.terminal,ts.terminal,gs.terminal,0)<>1) ELSE NULL END,
    'dependencies_within_project',COALESCE(bool_and(b.project_id IS NOT DISTINCT FROM (row_data->>'project_id')::bigint),true),
    'dependencies_within_tenant',COALESCE(bool_and(COALESCE(b.tenant_id=(row_data->>'tenant_id')::bigint,false)),true))
  FROM task_dependencies d JOIN tasks b ON b.id=d.blocker_id JOIN sprints s ON s.id=b.sprint_id
  LEFT JOIN LATERAL (SELECT terminal FROM sprint_task_statuses
    WHERE sprint_id=b.sprint_id AND status_key=b.status ORDER BY id DESC LIMIT 1) ws ON true
  LEFT JOIN LATERAL (SELECT terminal FROM sprint_type_task_statuses WHERE sprint_type_key=s.sprint_type
    AND status_key=b.status AND (tenant_id=b.tenant_id OR tenant_id IS NULL)
    ORDER BY CASE WHEN tenant_id IS NULL THEN 0 ELSE 1 END DESC,id DESC LIMIT 1) ts ON true
  LEFT JOIN task_statuses gs ON gs.name=b.status
  WHERE d.blocked_id=(row_data->>'id')::bigint
$$;

CREATE FUNCTION telemetry_schema_snapshot(raw text) RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
  SELECT jsonb_build_object('fields',COALESCE(jsonb_agg(telemetry_pick(value,
    ARRAY['key','type','label','options','required','system'])),'[]'::jsonb))
  FROM jsonb_array_elements(CASE WHEN jsonb_typeof(telemetry_json(raw)->'fields')='array'
    THEN telemetry_json(raw)->'fields' ELSE '[]'::jsonb END)
  WHERE jsonb_typeof(value)='object'
$$;

CREATE FUNCTION telemetry_task_snapshot(row_data jsonb) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
  result jsonb; wf jsonb; schema_row record; descriptor jsonb;
  descriptors jsonb := '{}'::jsonb; custom_values jsonb := '{}'::jsonb;
  raw_custom jsonb; field_key text; field_value jsonb; incomplete boolean := false;
BEGIN
  result := telemetry_pick(row_data, ARRAY['id','status','priority','story_points','retry_count',
    'total_dispatch_count','manual_intervention_count','created_at','updated_at','project_id',
    'task_type','agent_id','assigned_agent_id','active_instance_id','origin_task_id','paused_at']);
  result := result || jsonb_build_object('title',left(row_data->>'title',8192)) || telemetry_dependency_state(row_data);
  SELECT to_jsonb(s) INTO wf FROM sprints s
    WHERE id = (row_data->>'sprint_id')::bigint AND tenant_id = (row_data->>'tenant_id')::bigint;
  result := result || jsonb_build_object('workflow_id',row_data->'sprint_id',
    'workflow_type',wf->'sprint_type','workflow_status',wf->'status');
  FOR schema_row IN SELECT id, schema_json FROM task_field_schemas
    WHERE tenant_id = (row_data->>'tenant_id')::bigint
      AND sprint_type_key = wf->>'sprint_type'
      AND (task_type IS NULL OR task_type = row_data->>'task_type')
    ORDER BY task_type NULLS FIRST, id
  LOOP
    IF jsonb_typeof(telemetry_json(schema_row.schema_json)->'fields') = 'array' THEN
      FOR descriptor IN SELECT value FROM jsonb_array_elements(telemetry_json(schema_row.schema_json)->'fields') LOOP
        field_key := descriptor->>'key';
        IF field_key IS NOT NULL AND COALESCE(descriptor->>'type','text') IN ('text','textarea','url','select','number','checkbox') THEN
          descriptors := descriptors || jsonb_build_object(field_key,
            telemetry_pick(descriptor, ARRAY['key','type','label','options']) || jsonb_build_object(
              'type',COALESCE(descriptor->>'type','text'),'schema_id',schema_row.id,'schema_fingerprint',md5(schema_row.schema_json)));
        END IF;
      END LOOP;
    END IF;
  END LOOP;
  raw_custom := telemetry_json(row_data->>'custom_fields_json');
  FOR field_key, descriptor IN SELECT key,value FROM jsonb_each(descriptors) LOOP
    field_value := raw_custom->field_key;
    IF jsonb_typeof(field_value) IN ('string','number','boolean','null') THEN
      IF octet_length(field_value::text) <= 8192 THEN
        custom_values := custom_values || jsonb_build_object(field_key,
          CASE WHEN descriptor->>'type'='number' AND jsonb_typeof(field_value)='number'
            THEN jsonb_build_object('decimal',field_value::text) ELSE field_value END);
      ELSE incomplete := true;
      END IF;
    ELSIF field_value IS NOT NULL THEN incomplete := true;
    END IF;
  END LOOP;
  IF jsonb_typeof(raw_custom) IS DISTINCT FROM 'object' THEN incomplete := true; END IF;
  RETURN result || jsonb_build_object('custom_fields',custom_values,'field_descriptors',
    (SELECT COALESCE(jsonb_agg(value),'[]'::jsonb) FROM jsonb_each(descriptors)),
    'fields_complete',NOT incomplete);
END $$;

-- Dependency counts are task facts derived from configured terminality. Emit a
-- new snapshot when an edge, blocker state or terminality definition changes.
-- The previous captured value is the before value; absent history stays null.
CREATE FUNCTION telemetry_refresh_dependencies(affected_ids bigint[], source_prefix text, cause text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE target record; after_state jsonb; before_state jsonb; prior_count jsonb; prior_scope jsonb; row_id bigint;
BEGIN
  FOR target IN SELECT t.* FROM tasks t WHERE t.id=ANY(affected_ids) AND t.tenant_id IS NOT NULL ORDER BY t.id LOOP
    -- Two different prerequisites can resolve concurrently. Serialize the
    -- dependent snapshot, without locking the dependent's canonical task row.
    PERFORM pg_advisory_xact_lock(hashtextextended('telemetry-dependencies:'||target.id,0));
    after_state := telemetry_task_snapshot(to_jsonb(target));
    IF octet_length(after_state::text)>100000 THEN
      after_state := telemetry_pick(after_state,ARRAY['id','status','project_id','workflow_id','workflow_type','task_type',
        'unresolved_dependencies','dependencies_within_project','dependencies_within_tenant']) || jsonb_build_object('fields_complete',false);
    END IF;
    SELECT payload->'after'->'unresolved_dependencies',payload->'after'->'dependencies_within_project'
      INTO prior_count,prior_scope FROM telemetry_outbox
      WHERE tenant_id=target.tenant_id AND task_id=target.id AND entity_type='task'
        AND payload->'after' ? 'unresolved_dependencies' ORDER BY id DESC LIMIT 1;
    IF prior_count IS NOT DISTINCT FROM after_state->'unresolved_dependencies'
      AND prior_scope IS NOT DISTINCT FROM after_state->'dependencies_within_project' THEN CONTINUE; END IF;
    before_state := after_state || jsonb_build_object('unresolved_dependencies',prior_count,
      'dependencies_within_project',prior_scope);
    row_id := nextval(pg_get_serial_sequence('telemetry_outbox','id'));
    INSERT INTO telemetry_outbox(id,tenant_id,source,source_key,entity_type,entity_id,task_id,project_id,workflow_id,
      agent_id,kind,occurred_at,causation_id,payload)
    VALUES(row_id,target.tenant_id,'task_dependencies',source_prefix||':'||target.id,'task',target.id,target.id,
      target.project_id,target.sprint_id,target.agent_id,'task.dependencies_changed',clock_timestamp(),cause,
      jsonb_build_object('before',before_state,'after',after_state,'context',after_state,
        'changed_fields',jsonb_build_array('unresolved_dependencies'),'dependency_history_complete',prior_count IS NOT NULL));
  END LOOP;
END $$;

CREATE FUNCTION telemetry_run_snapshot(row_data jsonb) RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE result jsonb; agent_snapshot jsonb;
BEGIN
  result := telemetry_pick(row_data, ARRAY['id','agent_id','task_id','status','created_at','dispatched_at',
    'completed_at','started_at','task_outcome','token_input','token_output','token_total',
    'effective_model','effective_thinking_level','effective_fast_mode','failure_class','failure_stage',
    'runtime_ended_at','runtime_end_success','runtime_end_source','lifecycle_outcome_posted_at',
    'runtime_completed_at','lifecycle_handoff_status','semantic_outcome_missing']);
  SELECT jsonb_build_object('instructions_version',a.instructions_version,
    'instructions_fingerprint',md5(a.job_instructions),'runtime_type',a.runtime_type)
    INTO agent_snapshot FROM agents a
    WHERE a.id = (row_data->>'agent_id')::bigint AND a.tenant_id = (row_data->>'tenant_id')::bigint;
  RETURN result || jsonb_build_object('agent_config_at_observation',agent_snapshot);
END $$;

CREATE FUNCTION telemetry_capture_change() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  old_row jsonb := '{}'::jsonb; new_row jsonb := '{}'::jsonb; row_data jsonb;
  old_safe jsonb := '{}'::jsonb; new_safe jsonb := '{}'::jsonb; task_row jsonb; instance_row jsonb;
  tenant bigint; task bigint; project bigint; workflow bigint; agent bigint; entity bigint;
  entity_kind text; event_kind text; key_text text; old_tenant bigint;
  now_at timestamptz := clock_timestamp(); happened_at timestamptz;
  payload_data jsonb; changed jsonb; outbox_id bigint; other_tenant bigint; affected_ids bigint[];
  supersedes_key text; previous_payload jsonb; previous_cause text; previous_time timestamptz;
  previous_project bigint; previous_workflow bigint; previous_agent bigint;
  config_keys text[] := ARRAY['id','key','name','status','status_key','label','terminal','is_default_entry',
    'stage_order','sprint_id','sprint_type','sprint_type_key','project_id','task_type','from_status',
    'to_status','outcome','outcome_key','field_name','requirement_type','match_field','severity','enabled',
    'priority','agent_id','source','event_name','action_kind','action_target','behavior','relationship_type_key',
    'category','affects_dispatch_eligibility','direction_semantics','active_statuses_json','resolved_statuses_json',
    'allowed_transitions_json','status_includes_json','status_excludes_json','model','instructions_version','runtime_type'];
BEGIN
  IF TG_OP <> 'INSERT' THEN old_row := to_jsonb(OLD); END IF;
  IF TG_OP <> 'DELETE' THEN new_row := to_jsonb(NEW); END IF;
  row_data := CASE WHEN TG_OP = 'DELETE' THEN old_row ELSE new_row END;
  tenant := (row_data->>'tenant_id')::bigint;
  entity := (row_data->>'id')::bigint;
  task := COALESCE((row_data->>'task_id')::bigint,
    (row_data->>'source_task_id')::bigint,(row_data->>'blocked_id')::bigint);
  workflow := (row_data->>'sprint_id')::bigint;
  project := (row_data->>'project_id')::bigint;
  agent := (row_data->>'agent_id')::bigint;
  IF TG_TABLE_NAME='projects' THEN project:=entity;
  ELSIF TG_TABLE_NAME='sprints' THEN workflow:=entity;
  ELSIF TG_TABLE_NAME='agents' THEN agent:=entity; END IF;
  entity_kind := 'configuration';
  event_kind := 'configuration.changed';
  happened_at := now_at;

  IF TG_OP='DELETE' AND TG_TABLE_NAME IN ('job_instances','runtime_executions') THEN
    entity_kind := CASE TG_TABLE_NAME WHEN 'job_instances' THEN 'run' ELSE 'runtime_execution' END;
    tenant := COALESCE(tenant,(SELECT tenant_id FROM telemetry_outbox
      WHERE entity_type=entity_kind AND entity_id=entity LIMIT 1));
    DELETE FROM telemetry_outbox WHERE entity_type=entity_kind AND entity_id=entity;
    DELETE FROM telemetry_observations WHERE entity_type=entity_kind AND entity_id=entity;
    IF tenant IS NOT NULL AND to_regclass('public.telemetry_query_results') IS NOT NULL THEN
      EXECUTE 'DELETE FROM telemetry_query_results WHERE tenant_id = $1' USING tenant;
    END IF;
    RETURN NULL;
  END IF;

  IF TG_TABLE_NAME = 'task_statuses' THEN
    IF TG_OP='UPDATE' AND old_row->'terminal' IS NOT DISTINCT FROM new_row->'terminal'
      AND old_row->'name' IS NOT DISTINCT FROM new_row->'name' THEN RETURN NULL; END IF;
    SELECT array_agg(DISTINCT blocked_id) INTO affected_ids FROM task_dependencies;
    outbox_id := nextval(pg_get_serial_sequence('telemetry_outbox','id'));
    PERFORM telemetry_refresh_dependencies(affected_ids,'global-terminality:'||outbox_id,
      NULLIF(current_setting('agent_hq.telemetry_causation_id',true),''));
    RETURN NULL;
  END IF;

  IF TG_TABLE_NAME = 'tasks' THEN
    task := entity;
    task_row := row_data;
    IF tenant IS NULL THEN SELECT tenant_id INTO tenant FROM sprints WHERE id = workflow; END IF;
    -- A hard deletion follows the canonical retention policy. Keep a minimal
    -- tombstone, never the deleted task's custom fields or frozen proof data.
    IF TG_OP = 'DELETE' THEN
      DELETE FROM telemetry_outbox WHERE task_id = task;
      DELETE FROM telemetry_observations WHERE task_id = task;
      IF to_regclass('public.telemetry_query_results') IS NOT NULL THEN
        EXECUTE 'DELETE FROM telemetry_query_results WHERE tenant_id = $1' USING tenant;
      END IF;
      old_safe := jsonb_build_object('id',task);
    ELSE
      new_safe := telemetry_task_snapshot(new_row || jsonb_build_object('tenant_id',tenant));
      IF TG_OP = 'UPDATE' THEN
        old_safe := telemetry_task_snapshot(old_row || jsonb_build_object('tenant_id',COALESCE((old_row->>'tenant_id')::bigint,tenant)));
      END IF;
    END IF;
    entity_kind := 'task';
    event_kind := CASE TG_OP WHEN 'INSERT' THEN 'task.created' WHEN 'DELETE' THEN 'task.deleted' ELSE 'task.changed' END;
    old_tenant := (old_row->>'tenant_id')::bigint;
    IF old_tenant IS NOT NULL AND old_tenant <> tenant THEN
      DELETE FROM telemetry_outbox WHERE task_id = task;
      DELETE FROM telemetry_observations WHERE task_id = task;
      old_safe := '{}'::jsonb;
      event_kind := 'task.bootstrap';
    END IF;
  ELSIF TG_TABLE_NAME = 'job_instances' THEN
    entity_kind := 'run';
    event_kind := CASE TG_OP WHEN 'INSERT' THEN 'run.created' WHEN 'DELETE' THEN 'run.deleted' ELSE 'run.changed' END;
    IF TG_OP <> 'DELETE' THEN new_safe := telemetry_run_snapshot(new_row); END IF;
    IF TG_OP <> 'INSERT' THEN old_safe := telemetry_run_snapshot(old_row); END IF;
  ELSIF TG_TABLE_NAME = 'runtime_executions' THEN
    SELECT to_jsonb(j) INTO instance_row FROM job_instances j WHERE id = (row_data->>'instance_id')::bigint;
    task := (instance_row->>'task_id')::bigint;
    agent := (instance_row->>'agent_id')::bigint;
    entity_kind := 'runtime_execution';
    event_kind := CASE TG_OP WHEN 'INSERT' THEN 'runtime.created' WHEN 'DELETE' THEN 'runtime.deleted' ELSE 'runtime.changed' END;
    new_safe := telemetry_pick(new_row,ARRAY['id','instance_id','runtime_type','driver','backend','state',
      'boundary_version','boundary_fingerprint','started_at','ended_at','created_at']);
    old_safe := telemetry_pick(old_row,ARRAY['id','instance_id','runtime_type','driver','backend','state',
      'boundary_version','boundary_fingerprint','started_at','ended_at','created_at']);
    happened_at := telemetry_timestamp(row_data->>'ended_at',now_at);
  ELSIF TG_TABLE_NAME = 'task_history' THEN
    -- Canonical task mutations already capture status/fields. Only the accepted
    -- semantic outcome is distinct evidence; notes/error strings are excluded.
    IF row_data->>'field' <> 'lifecycle_outcome' OR TG_OP = 'DELETE' THEN RETURN NULL; END IF;
    entity_kind := 'task'; entity := task; event_kind := 'task.outcome';
    new_safe := jsonb_build_object('outcome',row_data->'new_value');
    old_safe := jsonb_build_object('outcome',old_row->'new_value');
  ELSIF TG_TABLE_NAME = 'external_task_event_receipts' THEN
    -- Only accepted receipts represent an event, not every request/retry.
    IF row_data->>'processing_state' NOT IN ('processed','applied','ignored','completed') OR TG_OP = 'DELETE' THEN RETURN NULL; END IF;
    entity_kind := 'task'; entity := task; event_kind := 'task.external_event';
    new_safe := telemetry_pick(new_row,ARRAY['source','event','processing_state','mapping_id','mapping_action_kind','mapping_action_target','fingerprint']);
    old_safe := telemetry_pick(old_row,ARRAY['source','event','processing_state','mapping_id','mapping_action_kind','mapping_action_target','fingerprint']);
  ELSIF TG_TABLE_NAME IN ('task_relationships','task_dependencies') THEN
    entity_kind := 'task'; entity := task;
    event_kind := CASE TG_OP WHEN 'INSERT' THEN 'task.relationship_added' WHEN 'DELETE' THEN 'task.relationship_removed' ELSE 'task.relationship_changed' END;
    new_safe := telemetry_pick(new_row,ARRAY['source_task_id','target_task_id','relationship_type_key','blocker_id','blocked_id']);
    old_safe := telemetry_pick(old_row,ARRAY['source_task_id','target_task_id','relationship_type_key','blocker_id','blocked_id']);
    SELECT tenant_id INTO other_tenant FROM tasks WHERE id = COALESCE((row_data->>'target_task_id')::bigint,(row_data->>'blocker_id')::bigint);
  ELSIF TG_TABLE_NAME = 'task_field_schemas' THEN
    new_safe := telemetry_pick(new_row,ARRAY['id','sprint_type_key','task_type']) || jsonb_build_object('schema',telemetry_schema_snapshot(new_row->>'schema_json'));
    old_safe := telemetry_pick(old_row,ARRAY['id','sprint_type_key','task_type']) || jsonb_build_object('schema',telemetry_schema_snapshot(old_row->>'schema_json'));
  ELSIF TG_TABLE_NAME = 'routing_config_audit_log' THEN
    IF TG_OP <> 'INSERT' THEN RETURN NULL; END IF;
    workflow := (row_data->>'workflow_id')::bigint;
    new_safe := telemetry_pick(row_data,ARRAY['entity_table','entity_id','entity_key','action','workflow_type','workflow_id','batch_id']) ||
      jsonb_build_object('before_fingerprint',md5(row_data->>'before_json'),'after_fingerprint',md5(row_data->>'after_json'));
    old_safe := '{}'::jsonb;
  ELSE
    new_safe := telemetry_pick(new_row,config_keys);
    old_safe := telemetry_pick(old_row,config_keys);
    IF TG_TABLE_NAME = 'agents' THEN
      new_safe := new_safe || jsonb_build_object('instructions_fingerprint',md5(new_row->>'job_instructions'));
      old_safe := old_safe || jsonb_build_object('instructions_fingerprint',md5(old_row->>'job_instructions'));
    END IF;
    IF TG_OP = 'DELETE' AND TG_TABLE_NAME IN ('projects','sprints','agents') THEN
      -- Honor canonical entity retention, including historical run snapshots.
      IF TG_TABLE_NAME = 'projects' THEN
        DELETE FROM telemetry_outbox WHERE tenant_id=tenant AND project_id=entity;
        DELETE FROM telemetry_observations WHERE tenant_id=tenant AND project_id=entity;
        project := entity;
      ELSIF TG_TABLE_NAME = 'sprints' THEN
        DELETE FROM telemetry_outbox WHERE tenant_id=tenant AND workflow_id=entity;
        DELETE FROM telemetry_observations WHERE tenant_id=tenant AND workflow_id=entity;
        workflow := entity;
      ELSE
        DELETE FROM telemetry_outbox WHERE tenant_id=tenant AND
          ((agent_id=entity AND entity_type IN ('run','runtime_execution')) OR (source='agents' AND entity_id=entity));
        DELETE FROM telemetry_observations WHERE tenant_id=tenant AND
          ((agent_id=entity AND entity_type IN ('run','runtime_execution')) OR (source='agents' AND entity_id=entity));
      END IF;
      IF to_regclass('public.telemetry_query_results') IS NOT NULL THEN
        EXECUTE 'DELETE FROM telemetry_query_results WHERE tenant_id = $1' USING tenant;
      END IF;
      old_safe := jsonb_build_object('id',entity);
      new_safe := '{}'::jsonb;
      event_kind := 'configuration.deleted';
    END IF;
  END IF;

  IF task IS NOT NULL AND task_row IS NULL THEN SELECT to_jsonb(t) INTO task_row FROM tasks t WHERE id = task; END IF;
  IF task_row IS NOT NULL THEN
    IF tenant IS NOT NULL AND (task_row->>'tenant_id')::bigint IS NOT NULL
      AND tenant <> (task_row->>'tenant_id')::bigint THEN RETURN NULL; END IF;
    tenant := COALESCE(tenant,(task_row->>'tenant_id')::bigint);
    project := (task_row->>'project_id')::bigint;
    workflow := (task_row->>'sprint_id')::bigint;
    agent := COALESCE(agent,(task_row->>'agent_id')::bigint);
  END IF;
  IF tenant IS NULL AND workflow IS NOT NULL THEN
    SELECT tenant_id,project_id INTO tenant,project FROM sprints WHERE id = workflow;
  END IF;
  IF tenant IS NULL AND project IS NOT NULL THEN SELECT tenant_id INTO tenant FROM projects WHERE id = project; END IF;
  IF task_row IS NULL AND agent IS NOT NULL AND entity_kind IN ('run','runtime_execution') THEN
    SELECT tenant_id,project_id INTO other_tenant,project FROM agents WHERE id=agent;
    IF tenant IS NOT NULL AND other_tenant IS DISTINCT FROM tenant THEN RETURN NULL; END IF;
    tenant := COALESCE(tenant,other_tenant);
  END IF;
  IF tenant IS NULL AND agent IS NOT NULL THEN SELECT tenant_id INTO tenant FROM agents WHERE id = agent; END IF;
  -- Global legacy configuration has no tenant owner. It is discoverable in the
  -- catalog, but cannot silently be assigned to an arbitrary tenant's history.
  IF tenant IS NULL OR NOT EXISTS (SELECT 1 FROM tenants WHERE id = tenant) THEN RETURN NULL; END IF;
  IF other_tenant IS NOT NULL AND other_tenant <> tenant THEN RETURN NULL; END IF;
  -- Retained proofs embed source context. Ownership changes revoke those
  -- artifacts even when no task IDs exist (taskless run/agent reports).
  IF TG_OP='UPDATE' AND to_regclass('public.telemetry_query_results') IS NOT NULL
    AND TG_TABLE_NAME IN ('agents','sprints','job_instances','runtime_executions')
    AND (old_row->'tenant_id' IS DISTINCT FROM new_row->'tenant_id'
      OR old_row->'project_id' IS DISTINCT FROM new_row->'project_id'
      OR old_row->'task_id' IS DISTINCT FROM new_row->'task_id'
      OR old_row->'agent_id' IS DISTINCT FROM new_row->'agent_id'
      OR old_row->'instance_id' IS DISTINCT FROM new_row->'instance_id') THEN
    EXECUTE 'DELETE FROM telemetry_query_results WHERE tenant_id=$1 OR tenant_id=$2'
      USING tenant,(old_row->>'tenant_id')::bigint;
  END IF;
  IF TG_OP = 'UPDATE' AND old_safe = new_safe
    AND NOT (TG_TABLE_NAME='task_history' AND old_row->'created_at' IS DISTINCT FROM new_row->'created_at') THEN RETURN NULL; END IF;

  IF TG_OP='UPDATE' AND (TG_TABLE_NAME='task_history' OR
    (TG_TABLE_NAME='runtime_executions' AND old_row->>'state' IN ('succeeded','failed','cancelled','lost')
      AND old_row->'state'=new_row->'state' AND old_row->'ended_at' IS DISTINCT FROM new_row->'ended_at')) THEN
    SELECT source_key,payload,causation_id,occurred_at,project_id,workflow_id,agent_id
      INTO supersedes_key,previous_payload,previous_cause,previous_time,previous_project,previous_workflow,previous_agent
      FROM telemetry_outbox WHERE tenant_id=tenant AND source=TG_TABLE_NAME
        AND (source_key LIKE TG_TABLE_NAME||':'||(row_data->>'id')||':%'
          OR source_key='backfill:'||TG_TABLE_NAME||':'||(row_data->>'id')) ORDER BY id DESC LIMIT 1;
    IF supersedes_key IS NOT NULL THEN
      old_safe := COALESCE(previous_payload->'before','{}'::jsonb);
      project := previous_project; workflow := previous_workflow; agent := previous_agent;
      IF TG_TABLE_NAME='task_history' THEN
        happened_at := CASE WHEN old_row->'created_at' IS DISTINCT FROM new_row->'created_at'
          THEN telemetry_timestamp(new_row->>'created_at',previous_time) ELSE previous_time END;
      END IF;
    END IF;
  END IF;

  SELECT COALESCE(jsonb_agg(key),'[]'::jsonb) INTO changed FROM (
    SELECT key FROM jsonb_object_keys(old_safe || new_safe) key
    WHERE old_safe->key IS DISTINCT FROM new_safe->key
  ) fields;
  payload_data := jsonb_build_object('before',old_safe,'after',new_safe,'changed_fields',changed,
    'context',CASE WHEN task_row IS NULL AND entity_kind IN ('run','runtime_execution')
      THEN jsonb_build_object('project_id',project,'agent_id',agent,'task_id',task)
      WHEN task_row IS NULL OR (TG_TABLE_NAME = 'tasks' AND TG_OP = 'DELETE')
      THEN '{}'::jsonb ELSE telemetry_task_snapshot(task_row || jsonb_build_object('tenant_id',tenant)) END,
    'transaction_id',txid_current()::text,
    'outcome_agent_id',NULLIF(current_setting('agent_hq.telemetry_outcome_agent_id',true),'')::bigint);
  IF supersedes_key IS NOT NULL THEN payload_data := payload_data || jsonb_build_object(
    'supersedes_source_key',supersedes_key,'context',COALESCE(previous_payload->'context','{}'::jsonb),
    'outcome_agent_id',previous_payload->'outcome_agent_id',
    'historical_context_known',COALESCE(previous_payload->'historical_context_known','true'::jsonb)); END IF;
  -- An oversized declared schema cannot inflate every canonical mutation without
  -- bound. Preserve the lifecycle fact while making missing field proof explicit.
  IF octet_length(payload_data::text) > 262144 THEN
    payload_data := jsonb_build_object('before',telemetry_pick(old_safe,ARRAY['id','status','project_id','workflow_id','task_type']),
      'after',telemetry_pick(new_safe,ARRAY['id','status','project_id','workflow_id','task_type']),
      'changed_fields',changed,'fields_complete',false,'truncated',true);
  END IF;
  outbox_id := nextval(pg_get_serial_sequence('telemetry_outbox','id'));
  key_text := TG_TABLE_NAME || ':' || COALESCE((row_data->>'id'),md5(row_data::text)) || ':' || outbox_id::text;
  INSERT INTO telemetry_outbox(id,tenant_id,source,source_key,entity_type,entity_id,task_id,
    project_id,workflow_id,agent_id,kind,occurred_at,causation_id,payload)
  VALUES(outbox_id,tenant,TG_TABLE_NAME,key_text,entity_kind,COALESCE(entity,workflow,project,tenant),task,
    project,workflow,agent,event_kind,happened_at,
    COALESCE(NULLIF(current_setting('agent_hq.telemetry_causation_id',true),''),previous_cause),payload_data);

  IF TG_TABLE_NAME='tasks' AND TG_OP='UPDATE' AND
    (old_row->'status' IS DISTINCT FROM new_row->'status' OR old_row->'sprint_id' IS DISTINCT FROM new_row->'sprint_id') THEN
    SELECT array_agg(blocked_id) INTO affected_ids FROM task_dependencies WHERE blocker_id=task;
  ELSIF TG_TABLE_NAME='task_dependencies' THEN
    affected_ids := ARRAY[task];
  ELSIF TG_TABLE_NAME IN ('sprint_task_statuses','sprint_type_task_statuses') AND
    (TG_OP<>'UPDATE' OR old_row->'terminal' IS DISTINCT FROM new_row->'terminal' OR old_row->'status_key' IS DISTINCT FROM new_row->'status_key') THEN
    SELECT array_agg(DISTINCT d.blocked_id) INTO affected_ids FROM task_dependencies d
      JOIN tasks t ON t.id=d.blocked_id WHERE t.tenant_id=tenant;
  END IF;
  IF affected_ids IS NOT NULL THEN
    PERFORM telemetry_refresh_dependencies(affected_ids,'dependency-effect:'||outbox_id,
      NULLIF(current_setting('agent_hq.telemetry_causation_id',true),''));
  END IF;
  RETURN NULL;
END $$;

DO $$
DECLARE source_name text;
BEGIN
  FOREACH source_name IN ARRAY ARRAY['tasks','job_instances','runtime_executions','task_history',
    'external_task_event_receipts','task_relationships','task_dependencies','task_field_schemas',
    'routing_config_audit_log','agents','projects','sprints','sprint_types','sprint_task_routing_rules',
    'sprint_task_statuses','sprint_task_transition_requirements','sprint_task_transitions',
    'sprint_type_outcomes','sprint_type_relationship_types','sprint_type_task_statuses','sprint_type_task_types',
    'external_event_mappings','story_point_model_routing','routing_config','routing_transitions','task_statuses']
  LOOP
    INSERT INTO telemetry_capture_sources(source) VALUES(source_name);
    EXECUTE format('CREATE TRIGGER telemetry_capture AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION telemetry_capture_change()',source_name);
  END LOOP;
  INSERT INTO telemetry_capture_sources(source,limitations) VALUES
    ('task_events','Legacy best-effort transition events; historical context and completeness are unknown.');
END $$;

COMMIT;
