-- Agent HQ PostgreSQL baseline: tables
-- Generated by scripts/pg/generate-baseline-schema.mjs from dangling-repair.db
-- Do not edit by hand: regenerate from the snapshot instead.

CREATE TABLE agent_mcp_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  mcp_server_id bigint NOT NULL,
  overrides text NOT NULL DEFAULT '{}',
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE agent_mcp_capability_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  capability_key text NOT NULL,
  enabled bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE agent_tool_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  tool_id bigint NOT NULL,
  overrides text NOT NULL DEFAULT '{}',
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE agents (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  role text NOT NULL DEFAULT '',
  session_key text NOT NULL,
  workspace_path text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'idle' CHECK (status IN ('idle','running','blocked')),
  last_active text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  openclaw_agent_id text,
  model text,
  runtime_type text NOT NULL DEFAULT 'openclaw',
  runtime_config text,
  hooks_url text,
  preferred_provider text NOT NULL DEFAULT 'anthropic',
  slug text,
  os_user text,
  repo_path text,
  hooks_auth_header text,
  job_title text NOT NULL DEFAULT '',
  project_id bigint,
  sprint_id bigint,
  schedule text NOT NULL DEFAULT '',
  dispatch_mode text NOT NULL DEFAULT 'agentTurn',
  job_instructions text NOT NULL DEFAULT '',
  skill_name text,
  skill_names text NOT NULL DEFAULT '[]',
  enabled bigint NOT NULL DEFAULT 1,
  timeout_seconds bigint NOT NULL DEFAULT 900,
  github_identity_id bigint,
  stall_threshold_min bigint NOT NULL DEFAULT 30,
  max_retries bigint NOT NULL DEFAULT 3,
  sort_rules text NOT NULL DEFAULT '[]',
  startup_grace_seconds bigint,
  heartbeat_stale_seconds bigint,
  instructions_version bigint NOT NULL DEFAULT 0,
  system_role text,
  repo_url text,
  repo_access_mode text CHECK (repo_access_mode IN ('worktree','clone')),
  deleted_at text,
  job_instructions_updated_at text,
  tenant_id bigint,
  global_mcp_admin bigint NOT NULL DEFAULT 0,
  provider_connection_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE app_settings (
  key text,
  value text NOT NULL DEFAULT '',
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (key)
);

CREATE TABLE canonical_chat_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  channel text NOT NULL,
  session_key text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE chat_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  instance_id bigint,
  agent_id bigint,
  filename text NOT NULL,
  filepath text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size bigint NOT NULL DEFAULT 0,
  uploaded_by text NOT NULL DEFAULT 'user',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE chat_messages (
  id text,
  agent_id bigint NOT NULL,
  role text NOT NULL CHECK (role IN ('user','assistant','system','tool')),
  content text NOT NULL DEFAULT '',
  timestamp text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  session_key text NOT NULL DEFAULT '',
  instance_id bigint,
  event_type text NOT NULL DEFAULT 'text',
  event_meta text NOT NULL DEFAULT '{}',
  durable_run_id text,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE default_package_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  package_key text NOT NULL,
  package_version bigint NOT NULL,
  applied_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  mode text NOT NULL DEFAULT 'install',
  created_json text NOT NULL DEFAULT '{}',
  restored_json text NOT NULL DEFAULT '{}',
  updated_json text NOT NULL DEFAULT '{}',
  conflicts_json text NOT NULL DEFAULT '[]',
  PRIMARY KEY (id)
);

CREATE TABLE dev_db_sync_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  actor text NOT NULL,
  source_kind text NOT NULL,
  source_db_path text NOT NULL,
  target_environment_id text NOT NULL,
  target_db_path text NOT NULL,
  scope text NOT NULL,
  requested_task_id bigint NOT NULL,
  task_id bigint,
  synced_task_ids_json text NOT NULL,
  row_counts_json text NOT NULL,
  dry_run bigint NOT NULL DEFAULT 0,
  reason text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE dispatch_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint,
  dispatched_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  routing_reason text,
  candidate_count bigint,
  candidates_skipped text,
  agent_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE external_event_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint,
  source text,
  event_name text NOT NULL,
  task_type text,
  status_includes_json text NOT NULL DEFAULT '[]',
  status_excludes_json text NOT NULL DEFAULT '[]',
  action_kind text NOT NULL DEFAULT 'ignore',
  action_target text,
  apply_review_evidence bigint NOT NULL DEFAULT 0,
  apply_failure_detail bigint NOT NULL DEFAULT 0,
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  sprint_id bigint,
  sprint_type text,
  PRIMARY KEY (id)
);

CREATE TABLE external_task_event_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  fingerprint text NOT NULL,
  source text NOT NULL,
  event text NOT NULL,
  task_id bigint NOT NULL,
  environment_id text NOT NULL,
  queue_id text NOT NULL,
  lease_id text NOT NULL,
  branch text,
  commit_sha text,
  review_url text,
  message text NOT NULL,
  payload_json text NOT NULL,
  received_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  processed_at text,
  processing_state text NOT NULL DEFAULT 'received',
  processing_error text,
  mapping_id bigint,
  mapping_action_kind text,
  mapping_action_target text,
  request_metadata_json text,
  PRIMARY KEY (id)
);

CREATE TABLE github_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint,
  github_username text NOT NULL,
  token text NOT NULL DEFAULT '',
  git_author_name text NOT NULL DEFAULT '',
  git_author_email text NOT NULL DEFAULT '',
  lane text NOT NULL DEFAULT 'shared' CHECK (lane IN ('dev','qa','release','shared')),
  notes text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  last_validated_at text,
  validation_status text CHECK (validation_status IN (NULL,'valid','failed')),
  validation_error text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE instance_artifacts (
  instance_id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint,
  current_stage text NOT NULL DEFAULT 'dispatch' CHECK (current_stage IN ('dispatch','start','heartbeat','progress','blocker','completion')),
  summary text,
  latest_commit_hash text,
  branch_name text,
  changed_files_json text NOT NULL DEFAULT '[]',
  changed_files_count bigint,
  blocker_reason text,
  outcome text,
  last_agent_heartbeat_at text,
  last_meaningful_output_at text,
  started_at text,
  completed_at text,
  stale bigint NOT NULL DEFAULT 0,
  stale_at text,
  session_key text,
  last_note_at text,
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (instance_id)
);

CREATE TABLE integrity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  agent_id bigint,
  instance_id bigint,
  anomaly_type text NOT NULL CHECK (anomaly_type IN (
          'missing_review_evidence',
          'missing_qa_evidence',
          'commit_mismatch',
          'deployed_not_verified',
          'stale_outcome_write',
          'branch_missing_on_origin',
          'evidence_placeholder'
        )),
  detail text,
  resolved bigint NOT NULL DEFAULT 0,
  resolved_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE job_instances (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  task_id bigint,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','dispatched','running','done','failed','cancelled')),
  session_key text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  dispatched_at text,
  completed_at text,
  error text,
  artifact_summary text,
  run_stage text,
  last_heartbeat_at text,
  last_meaningful_output_at text,
  latest_commit_hash text,
  branch_name text,
  changed_files text,
  changed_files_count bigint,
  started_at text,
  blocker_reason text,
  abort_attempted_at text,
  abort_status text,
  abort_error text,
  task_outcome text,
  token_input bigint,
  token_output bigint,
  token_total bigint,
  effective_model text,
  payload_sent text,
  response text,
  run_id text,
  last_agent_heartbeat_at text,
  worktree_path text,
  failure_class text,
  failure_stage text,
  runtime_ended_at text,
  runtime_end_success bigint,
  runtime_end_error text,
  runtime_end_source text,
  lifecycle_outcome_posted_at text,
  effective_thinking_level text,
  runtime_completed_at text,
  lifecycle_handoff_status text,
  semantic_outcome_missing bigint NOT NULL DEFAULT 0,
  durable_run_id text,
  effective_fast_mode bigint CHECK (effective_fast_mode IN (0, 1)),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE lifecycle_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_type text,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  instance_id bigint,
  agent_id bigint,
  job_title text NOT NULL DEFAULT '',
  level text NOT NULL DEFAULT 'info' CHECK (level IN ('info','warn','error','debug')),
  message text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE mcp_api_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  agent_id bigint NOT NULL,
  name text NOT NULL DEFAULT '',
  key_prefix text NOT NULL DEFAULT '',
  key_hash text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  last_used_at text,
  revoked_at text,
  tenant_id bigint,
  global_admin bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE mcp_servers (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL DEFAULT '',
  transport text NOT NULL DEFAULT 'stdio' CHECK (transport IN ('stdio')),
  command text NOT NULL,
  args text NOT NULL DEFAULT '[]',
  env text NOT NULL DEFAULT '{}',
  cwd text,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE notification_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  source text,
  outlet text,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE openclaw_transcript_ingest_state (
  instance_id bigint GENERATED BY DEFAULT AS IDENTITY,
  session_file text NOT NULL,
  last_line_index bigint NOT NULL DEFAULT 0,
  last_event_at text,
  last_heartbeat_at text,
  last_meaningful_output_at text,
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (instance_id)
);

CREATE TABLE project_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  entity_type text NOT NULL CHECK (entity_type IN ('project', 'sprint', 'job_template')),
  entity_id bigint NOT NULL,
  action text NOT NULL CHECK (action IN ('created', 'updated', 'deleted')),
  actor text NOT NULL DEFAULT 'system',
  changes text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE project_file_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint NOT NULL,
  file_id bigint NOT NULL,
  version_number bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  created_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  change_source text NOT NULL DEFAULT 'api',
  PRIMARY KEY (id)
);

CREATE TABLE project_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  uploaded_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by text NOT NULL DEFAULT 'manual',
  updated_at text NOT NULL DEFAULT '',
  current_version bigint NOT NULL DEFAULT 1,
  current_version_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  context_md text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  repo_path text,
  repo_url text,
  repo_access_mode text CHECK (repo_access_mode IN ('worktree','clone')),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE provider_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint,
  slug text NOT NULL CHECK (slug IN ('anthropic','openai','google','openrouter','ollama','openai-codex','mlx-studio','minimax')),
  display_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','connected','failed')),
  config text NOT NULL DEFAULT '{}',
  last_validated_at text,
  validation_error text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE provider_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  provider_slug text NOT NULL,
  auth_mode text NOT NULL,
  runtime_type text NOT NULL,
  external_ref text NOT NULL,
  display_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','connected','failed')),
  metadata text NOT NULL DEFAULT '{}',
  last_validated_at text,
  validation_error text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE recurring_task_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  series_id bigint NOT NULL,
  scheduled_for text NOT NULL,
  created_task_id bigint,
  status text NOT NULL CHECK (status IN ('started','created','skipped','failed')),
  error_message text,
  started_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  finished_at text,
  idempotency_key text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE recurring_task_series (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  sprint_id bigint NOT NULL,
  title_template text NOT NULL,
  description_template text NOT NULL DEFAULT '',
  task_type text NOT NULL,
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
  story_points bigint NOT NULL,
  status_on_create text NOT NULL CHECK (status_on_create IN ('todo','ready','in_progress','dev_deploy_queued','dev_deploying','review','qa_pass','ready_to_merge','deployed','done','needs_attention','cancelled','stalled','failed','blocked')),
  schedule_expression text NOT NULL,
  timezone text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  next_run_at text,
  last_run_at text,
  overlap_policy text NOT NULL DEFAULT 'skip_if_active' CHECK (overlap_policy IN ('skip_if_active','create_anyway')),
  agent_id bigint,
  created_by text NOT NULL DEFAULT 'system',
  updated_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE routing_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE routing_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  lane text NOT NULL DEFAULT 'default',
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  task_type text,
  priority bigint NOT NULL DEFAULT 0,
  is_protected bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE schema_migrations (
  id text,
  checksum text NOT NULL,
  applied_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  applied_by text NOT NULL DEFAULT 'agent-hq-api',
  app_commit text NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);

CREATE TABLE security_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  event_type text NOT NULL DEFAULT 'workspace_boundary_violation',
  agent_id bigint,
  instance_id bigint,
  task_id bigint,
  details text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE session_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  session_id bigint NOT NULL,
  ordinal bigint NOT NULL,
  role text NOT NULL CHECK (role IN ('user','assistant','system','tool')),
  event_type text NOT NULL DEFAULT 'text',
  content text NOT NULL DEFAULT '',
  event_meta text NOT NULL DEFAULT '{}',
  raw_payload text,
  timestamp text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  external_key text NOT NULL,
  runtime text NOT NULL,
  agent_id bigint,
  task_id bigint,
  instance_id bigint,
  project_id bigint,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','failed','abandoned')),
  title text NOT NULL DEFAULT '',
  started_at text,
  ended_at text,
  message_count bigint NOT NULL DEFAULT 0,
  token_input bigint,
  token_output bigint,
  metadata text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL DEFAULT 1,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT 'atlas' CHECK (source IN ('atlas','workspace','system')),
  fs_path text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_routing_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint,
  project_id bigint,
  sprint_type text,
  task_type text,
  status text NOT NULL,
  agent_id bigint,
  priority bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint NOT NULL,
  status_key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  terminal bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  allowed_transitions_json text NOT NULL DEFAULT '[]',
  stage_order bigint NOT NULL DEFAULT 0,
  is_default_entry bigint NOT NULL DEFAULT 0,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_transition_requirement_tombstones (
  sprint_id bigint NOT NULL,
  task_type_key text NOT NULL DEFAULT '',
  outcome text NOT NULL,
  field_name text NOT NULL,
  requirement_type text NOT NULL,
  match_field_key text NOT NULL DEFAULT '',
  deleted_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (sprint_id, task_type_key, outcome, field_name, requirement_type, match_field_key)
);

CREATE TABLE sprint_task_transition_requirements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint,
  project_id bigint,
  sprint_type text,
  task_type text,
  outcome text NOT NULL,
  field_name text NOT NULL,
  requirement_type text NOT NULL DEFAULT 'required' CHECK (requirement_type IN ('required','match','from_status')),
  match_field text,
  severity text NOT NULL DEFAULT 'block' CHECK (severity IN ('block','warn')),
  message text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_task_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  sprint_id bigint,
  project_id bigint,
  sprint_type text,
  task_type text,
  from_status text NOT NULL,
  outcome text NOT NULL,
  to_status text NOT NULL,
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  is_protected bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_outcomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  task_type text,
  outcome_key text NOT NULL,
  label text NOT NULL,
  description text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  behavior text NOT NULL DEFAULT 'base' CHECK (behavior IN ('base','extend','override','disable')),
  badge_variant text,
  stage_order bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 1,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_relationship_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  key text NOT NULL,
  label text NOT NULL,
  inverse_label text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'informational',
  affects_dispatch_eligibility bigint NOT NULL DEFAULT 0,
  direction_semantics text NOT NULL DEFAULT 'informational' CHECK (direction_semantics IN ('target_blocks_source','source_blocks_target','informational')),
  active_statuses_json text NOT NULL DEFAULT '[]',
  resolved_statuses_json text NOT NULL DEFAULT '[]',
  allow_create_related_task bigint NOT NULL DEFAULT 0,
  default_related_task_type text,
  default_related_task_status text,
  is_system bigint NOT NULL DEFAULT 1,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_task_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  status_key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  terminal bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  allowed_transitions_json text NOT NULL DEFAULT '[]',
  stage_order bigint NOT NULL DEFAULT 0,
  is_default_entry bigint NOT NULL DEFAULT 0,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_type_task_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  task_type text NOT NULL,
  is_system bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  key text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  is_system bigint NOT NULL DEFAULT 1,
  status_seeded_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  repo_required bigint NOT NULL DEFAULT 0,
  project_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE sprint_workflow_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  template_id bigint NOT NULL,
  status_key text NOT NULL,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  stage_order bigint NOT NULL DEFAULT 0,
  terminal bigint NOT NULL DEFAULT 0,
  is_default_entry bigint NOT NULL DEFAULT 0,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_workflow_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  key text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  is_default bigint NOT NULL DEFAULT 1,
  is_system bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprint_workflow_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  template_id bigint NOT NULL,
  from_status_key text NOT NULL,
  to_status_key text NOT NULL,
  transition_key text NOT NULL,
  label text NOT NULL,
  outcome text,
  stage_order bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 1,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE sprints (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id bigint NOT NULL,
  name text NOT NULL,
  goal text NOT NULL DEFAULT '',
  sprint_type text NOT NULL DEFAULT 'generic',
  workflow_template_key text,
  status text NOT NULL DEFAULT 'planning' CHECK (status IN ('planning','active','paused','complete','closed')),
  length_kind text NOT NULL DEFAULT 'time' CHECK (length_kind IN ('time','runs')),
  length_value text NOT NULL DEFAULT '',
  started_at text,
  ended_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  task_policy_seeded_at text,
  tenant_id bigint,
  repo_path text,
  repo_url text,
  repo_access_mode text CHECK (repo_access_mode IN ('worktree','clone')),
  PRIMARY KEY (id)
);

CREATE TABLE story_point_model_routing (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  max_points bigint NOT NULL,
  provider text,
  model text NOT NULL,
  fallback_model text,
  max_turns bigint,
  max_budget_usd double precision,
  label text,
  created_at text DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  thinking_level text,
  project_id bigint,
  sprint_id bigint,
  sprint_type text,
  fast_mode bigint CHECK (fast_mode IN (0, 1)),
  tenant_id bigint,
  enabled bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

CREATE TABLE system_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  policy_key text NOT NULL,
  from_status text NOT NULL,
  to_status text NOT NULL,
  trigger_event text NOT NULL,
  classification text NOT NULL DEFAULT 'configurable',
  enabled bigint NOT NULL DEFAULT 1,
  threshold_seconds bigint,
  description text NOT NULL DEFAULT '',
  source_file text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  filename text NOT NULL,
  filepath text NOT NULL,
  mime_type text NOT NULL DEFAULT '',
  size bigint NOT NULL DEFAULT 0,
  uploaded_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_creation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  sprint_id bigint,
  job_id bigint,
  source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','skill','agent','api','import')),
  routing text NOT NULL DEFAULT '',
  confidence text NOT NULL DEFAULT '' CHECK (confidence IN ('','low','medium','high')),
  scope_size text NOT NULL DEFAULT '' CHECK (scope_size IN ('','xs','small','medium','large','xl')),
  assumptions text NOT NULL DEFAULT '',
  open_questions text NOT NULL DEFAULT '',
  needs_split bigint NOT NULL DEFAULT 0,
  expected_artifact text NOT NULL DEFAULT '',
  success_mode text NOT NULL DEFAULT '',
  raw_input text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  agent_id bigint,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_dependencies (
  blocker_id bigint NOT NULL,
  blocked_id bigint NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  sprint_id bigint,
  agent_id bigint,
  from_status text,
  to_status text NOT NULL,
  moved_by text NOT NULL DEFAULT 'system',
  move_type text NOT NULL DEFAULT 'automatic' CHECK (move_type IN ('automatic','outcome','manual','rescue','dispatch')),
  instance_id bigint,
  reason text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_field_schemas (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  sprint_type_key text NOT NULL,
  task_type text,
  schema_json text NOT NULL DEFAULT '{}',
  is_system bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE task_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  changed_by text NOT NULL DEFAULT 'system',
  field text NOT NULL,
  old_value text,
  new_value text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  author text NOT NULL DEFAULT 'system',
  content text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_outcome_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  project_id bigint,
  sprint_id bigint,
  job_id bigint,
  first_pass_qa bigint NOT NULL DEFAULT 0,
  reopened_count bigint NOT NULL DEFAULT 0,
  rerouted_count bigint NOT NULL DEFAULT 0,
  split_after_creation bigint NOT NULL DEFAULT 0,
  blocked_after_creation bigint NOT NULL DEFAULT 0,
  clarification_count bigint NOT NULL DEFAULT 0,
  notes_count bigint NOT NULL DEFAULT 0,
  cycle_time_hours double precision,
  outcome_quality text NOT NULL DEFAULT '' CHECK (outcome_quality IN ('','good','acceptable','poor')),
  failure_reasons text NOT NULL DEFAULT '[]',
  outcome_summary text NOT NULL DEFAULT '',
  recorded_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  agent_id bigint,
  spawned_defects bigint NOT NULL DEFAULT 0,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE task_relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  source_task_id bigint NOT NULL,
  target_task_id bigint NOT NULL,
  relationship_type_key text NOT NULL,
  metadata_json text NOT NULL DEFAULT '{}',
  created_by text NOT NULL DEFAULT 'system',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id),
  CHECK (source_task_id != target_task_id)
);

CREATE TABLE task_statuses (
  name text,
  label text NOT NULL,
  color text NOT NULL DEFAULT 'slate',
  terminal bigint NOT NULL DEFAULT 0,
  is_system bigint NOT NULL DEFAULT 0,
  allowed_transitions text NOT NULL DEFAULT '[]',
  PRIMARY KEY (name)
);

CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'todo',
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
  project_id bigint,
  agent_id bigint,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  active_instance_id bigint,
  recurring bigint NOT NULL DEFAULT 0,
  sprint_id bigint NOT NULL,
  branch_url text,
  retry_count bigint NOT NULL DEFAULT 0,
  max_retries bigint NOT NULL DEFAULT 3,
  dispatched_at text,
  claimed_at text,
  routing_reason text,
  task_type text,
  story_points bigint,
  origin_task_id bigint,
  defect_type text,
  failure_class text,
  failure_detail text,
  review_owner_agent_id bigint,
  paused_at text,
  pause_reason text,
  first_dispatched_at text,
  total_dispatch_count bigint NOT NULL DEFAULT 0,
  manual_intervention_count bigint NOT NULL DEFAULT 0,
  previous_status text,
  custom_fields_json text NOT NULL DEFAULT '{}',
  recurring_series_id bigint,
  scheduled_for text,
  schedule_run_id bigint,
  generated_from text,
  assigned_agent_id bigint,
  tenant_id bigint,
  PRIMARY KEY (id)
);

CREATE TABLE telemetry_schema_config (
  id bigint DEFAULT 1,
  fields text NOT NULL DEFAULT '[]',
  description text NOT NULL DEFAULT '',
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE tenants (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  slug text NOT NULL,
  is_default bigint NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE tools (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL DEFAULT 1,
  name text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL DEFAULT '',
  implementation_type text NOT NULL DEFAULT 'bash' CHECK (implementation_type IN ('bash','shell','script','mcp','function','http')),
  implementation_body text NOT NULL DEFAULT '',
  input_schema text NOT NULL DEFAULT '{}',
  permissions text NOT NULL DEFAULT 'read_only' CHECK (permissions IN ('read_only','read_write','exec','network')),
  tags text NOT NULL DEFAULT '[]',
  enabled bigint NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE transition_requirements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_type text,
  outcome text NOT NULL,
  field_name text NOT NULL,
  requirement_type text NOT NULL DEFAULT 'required' CHECK (requirement_type IN ('required','match','from_status')),
  match_field text,
  severity text NOT NULL DEFAULT 'block' CHECK (severity IN ('block','warn')),
  message text NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  priority bigint NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (id)
);

CREATE TABLE workflow_file_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint NOT NULL,
  workflow_id bigint NOT NULL,
  file_id bigint NOT NULL,
  version_number bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  created_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  change_source text NOT NULL DEFAULT 'api',
  PRIMARY KEY (id)
);

CREATE TABLE workflow_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id bigint NOT NULL,
  project_id bigint NOT NULL,
  workflow_id bigint NOT NULL,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes bigint NOT NULL DEFAULT 0,
  file_path text NOT NULL,
  uploaded_by text NOT NULL DEFAULT 'manual',
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_by text NOT NULL DEFAULT 'manual',
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  current_version bigint NOT NULL DEFAULT 1,
  current_version_id bigint,
  PRIMARY KEY (id)
);
